Repository TakwimuAfrica/Takwimu, pull requests merged in 2018-08, with the labels that each got.

#287 Add beta highlight content on the homepage carousel box
  takwimu/static/img/icons/icon-notification.svg
  takwimu/templates/takwimu/_includes/homepage/beta_detail.html
  takwimu/templates/takwimu/_includes/homepage/hero.html
  takwimu/templates/takwimu/_includes/homepage/hero_detail.html
Labels: enhancement, frontend

#298 Fix: Country analysis section for sub-national level profile view
  takwimu/templates/profile/profile_detail.html
Labels: bug, frontend

#300 fix anchor navigation
  takwimu/templates/takwimu/_includes/profile/topic_detail.html
Labels: bug, frontend

#311 Change instagram icon to medium
  takwimu/templates/takwimu/_includes/navbar/about.html
Labels: bug, enhancement, frontend

#312 Update reference to bmgf
  README.md
  takwimu/templates/takwimu/_includes/footer.html
  takwimu/templates/takwimu/_includes/navbar/about.html
  takwimu/templates/takwimu/_includes/partners.html
Labels: documentation, enhancement, frontend

#309 Upgrade fontawesome to 5.2
  takwimu/templates/homepage.html
  takwimu/templates/profile/profile_detail.html
  takwimu/templates/takwimu/_layouts/_base.html
Labels: enhancement, frontend

#299 Add Crop Production data
  takwimu/profiles/census.py
  takwimu/profiles/takwimu.py
  takwimu/sql/crop_production_year.sql
  takwimu/sql/food_production.sql
  takwimu/sql/gdp_year.sql
  takwimu/sql/gni_year.sql
  takwimu/sql/hd_landscape.sql
  takwimu/sql/hiv_prevalence_year.sql
  takwimu/sql/life_expectancy_year.sql
  takwimu/sql/literacy.sql
  takwimu/sql/population_year.sql
  takwimu/sql/rank_year.sql
  takwimu/tables.py
  takwimu/templates/profile/no_data_available.html
  takwimu/templates/profile/profile_detail.html
Labels: backend, data, enhancement

#317 Make "About Us" button in navbar clickable
  takwimu/templates/takwimu/_includes/navbar/_index.html
  takwimu/templates/takwimu/_includes/navbar/about.html
  takwimu/templates/takwimu/_includes/sections/support-services/button.html
  takwimu/templates/takwimu/about/contact.html
Labels: enhancement, frontend

#314 Feature/topic page
  takwimu/models/dashboard.py
  takwimu/templates/takwimu/_includes/navbar/_index.html
  takwimu/templates/takwimu/_includes/sections/explore/_index.html
  takwimu/templates/takwimu/_includes/sections/explore/topics.html
  takwimu/templates/takwimu/topic_page.html
  takwimu/urls.py
  takwimu/views.py
Labels: backend, enhancement, frontend

#316 Feature/remove duplicate title
  takwimu/templates/takwimu/_includes/sections/support-services/tabs.html
Labels: bug, enhancement

#324 Fix carousel bullhorn
  takwimu/static/img/flags/beta.svg
  takwimu/templates/takwimu/_includes/homepage/beta_detail.html
  takwimu/templates/takwimu/_includes/homepage/carousel_item_detail.html
  takwimu/templates/takwimu/_includes/homepage/hero.html
  takwimu/templates/takwimu/_includes/homepage/hero_detail.html
Labels: bug, enhancement, frontend

#327 Update feedback text
  takwimu/templates/takwimu/_includes/homepage/carousel_item_detail.html
Labels: enhancement, frontend

#336 Enable country profile download as a document
  takwimu/migrations/0034_profilepage_document.py
  takwimu/models/dashboard.py
  takwimu/templates/takwimu/_includes/profile/country_profile_downloader.html
  takwimu/templates/takwimu/_includes/profile/hero.html
Labels: backend, enhancement

#328 Improve support design cards
  takwimu/templates/takwimu/about/support_services.html
Labels: enhancement, frontend

#329 Add grayscale in countries
  takwimu/templates/profile/profile_detail.html
  takwimu/templates/takwimu/_includes/sections/explore/countries.html
  takwimu/templates/takwimu/profile_page.html
Labels: enhancement, frontend

#326 Fix about us navbar dropdown
  README.md
  takwimu/static/css/takwimu.scss
  takwimu/static/img/logos/ap-footer-white.png
  takwimu/static/img/logos/ap-white.png
  takwimu/templates/takwimu/_includes/footer.html
  takwimu/templates/takwimu/_includes/navbar/_dropdown.html
  takwimu/templates/takwimu/_includes/navbar/_index.html
  takwimu/templates/takwimu/_includes/navbar/about.html
  takwimu/templates/takwimu/_includes/navbar/support_services.html
Labels: enhancement, frontend

#310 Data Request Template
  .github/ISSUE_TEMPLATE/data_request.md
Labels: data, documentation

#330 Tanzania causes of death data
  takwimu/profiles/census.py
  takwimu/sql/causes_of_death_over_five.sql
  takwimu/sql/causes_of_death_under_five.sql
  takwimu/sql/inpatient_diagnosis_over_five.sql
  takwimu/sql/inpatient_diagnosis_under_five.sql
  takwimu/sql/outpatient_diagnosis_over_five.sql
  takwimu/sql/outpatient_diagnosis_under_five.sql
  takwimu/tables.py
  takwimu/templates/profile/profile_detail.html
Labels: backend, data, enhancement

#338 Add Search
  docker-compose.yml
  docker-entrypoint.sh
  requirements.txt
  takwimu/models/dashboard.py
  takwimu/settings.py
  takwimu/templates/search_results.html
  takwimu/urls.py
  takwimu/views.py
Labels: backend, documentation, enhancement

#343 FAQ Ordering on Homepage
  takwimu/fixtures/faq.json
  takwimu/fixtures/faqsetting.json
  takwimu/migrations/0036_faqsetting.py
  takwimu/migrations/0037_faqsetting_data.py
  takwimu/models/dashboard.py
  takwimu/templates/takwimu/_includes/sections/faq/index.html
  takwimu/templates/takwimu/_includes/sections/faq/nav_detail.html
  takwimu/templates/takwimu/_includes/sections/faq/tab_detail.html
  takwimu/utils/db.py
  takwimu/wagtail_hooks.py
Labels: backend, enhancement
