Repository TakwimuAfrica/Takwimu, pull requests merged in 2018-07, with the labels that each got.

#131 Feature/active section state
  takwimu/static/css/takwimu.css
  takwimu/static/css/takwimu.scss
  takwimu/templates/takwimu/_includes/profile/sections_list.html
  takwimu/templates/takwimu/_includes/profile/sections_list_detail.html
Labels: design

#163 Feature - How it Works
  README.md
  takwimu/fixtures/explainersteps.json
  takwimu/fixtures/howitworks.json
  takwimu/migrations/0017_explainersteps.py
  takwimu/models/dashboard.py
  takwimu/templates/takwimu/_includes/sections/how-it-works/index.html
  takwimu/templates/takwimu/_includes/sections/how-it-works/nav_detail.html
  takwimu/templates/takwimu/_includes/sections/how-it-works/tab_detail.html
  takwimu/urls.py
  takwimu/views.py
  takwimu/wagtail_hooks.py
Labels: backend, enhancement, frontend

#165 Feature - Testimonials
  takwimu/fixtures/testimonials.json
  takwimu/migrations/0020_testimonial.py
  takwimu/models/dashboard.py
  takwimu/static/img/placeholder.jpg
  takwimu/templates/takwimu/_includes/sections/testimonials.html
  takwimu/views.py
  takwimu/wagtail_hooks.py
Labels: bug, enhancement

#166 Improve explore data by..
  takwimu/static/css/takwimu.scss
  takwimu/templates/takwimu/_includes/sections/explore/_index.html
  takwimu/templates/takwimu/_includes/sections/testimonials.html
  takwimu/templates/takwimu/_includes/sections/updates.html
  takwimu/templates/takwimu/home_page.html
  takwimu/templates/takwimu/profile_page.html
Labels: enhancement

#129 Explore data by topic section
  takwimu/context_processors.py
  takwimu/settings.py
  takwimu/templates/takwimu/_includes/sections/how-it-works/index.html
  takwimu/templates/takwimu/_includes/sections/topics/index.html
Labels: frontend

#178 Fix/topic design
  takwimu/templates/takwimu/_includes/profile/topic_detail.html
Labels: enhancement, frontend

#182 Feature/improve topic nav
  takwimu/static/css/takwimu.scss
  takwimu/templates/takwimu/_includes/profile/hero.html
  takwimu/templates/takwimu/_includes/sections/support-services/tabs.html
Labels: enhancement, frontend

#185 Add support services to About Page
  takwimu/fixtures/aboutus.json
  takwimu/migrations/0023_aboutussetting.py
  takwimu/models/dashboard.py
  takwimu/templates/takwimu/_includes/navbar/about.html
  takwimu/templates/takwimu/about/index.html
  takwimu/templates/takwimu/about_page.html
  takwimu/urls.py
  takwimu/views.py
Labels: enhancement, frontend

#198 [HURUmap] Override profile detail template
  takwimu/static/css/takwimu.scss
  takwimu/templates/profile/profile_detail.html
  takwimu/templates/profile/profile_detail_census.html
  takwimu/templates/profile/profile_detail_takwimu.html
  takwimu/urls.py
Labels: enhancement, frontend

#181 Add Support Services
  takwimu/context_processors.py
  takwimu/fixtures/howitworks.json
  takwimu/fixtures/services.json
  takwimu/fixtures/supportservice.json
  takwimu/migrations/0023_aboutussetting.py
  takwimu/migrations/0024_auto_20180717_1622.py
  takwimu/models/dashboard.py
  takwimu/settings.py
  takwimu/templates/takwimu/_includes/footer.html
  takwimu/templates/takwimu/_includes/navbar/_index.html
  takwimu/templates/takwimu/_includes/navbar/about.html
  takwimu/templates/takwimu/_includes/navbar/support_services.html
  takwimu/templates/takwimu/about/support-services.html
  takwimu/templates/takwimu/about/support_services.html
  takwimu/templates/takwimu/about_page.html
  takwimu/templates/takwimu/home_page.html
  takwimu/urls.py
  takwimu/views.py
  takwimu/wagtail_hooks.py
Labels: enhancement, frontend

#197 Replace dummy data with relevant content
  takwimu/templates/takwimu/_includes/partners.html
  takwimu/templates/takwimu/_includes/sections/updates.html
  takwimu/templates/takwimu/contact_us_page.html
Labels: enhancement, frontend

#199 Feature/improve toc design
  takwimu/static/css/takwimu.scss
  takwimu/static/img/icons/add.svg
  takwimu/static/img/icons/close.svg
  takwimu/static/img/icons/minus.svg
  takwimu/templates/takwimu/_includes/profile/country_selector.html
  takwimu/templates/takwimu/_includes/profile/hero.html
  takwimu/templates/takwimu/_includes/profile/toc_detail.html
Labels: enhancement, frontend

#206 Remove data link in navbar
  takwimu/templates/takwimu/_includes/navbar/_index.html
Labels: enhancement, frontend

#205 Option to hide Indicator Title
  takwimu/migrations/0025_auto_20180720_0724.py
  takwimu/models/dashboard.py
  takwimu/templates/takwimu/_includes/dataview/_base.html
Labels: backend, enhancement, frontend

#230 Update our services
  takwimu/templates/takwimu/_includes/navbar/support_services.html
Labels: bug, enhancement

#231 Add box-shadow in a card
  takwimu/templates/takwimu/about/support_services.html
Labels: bug, enhancement, frontend

#232 Add mega drop shadow
  takwimu/templates/takwimu/_includes/navbar/_dropdown.html
  takwimu/templates/takwimu/_includes/navbar/about.html
Labels: bug, enhancement, frontend

#234 Improve navbar design
  takwimu/templates/takwimu/_includes/navbar/_index.html
  takwimu/templates/takwimu/_includes/navbar/support_services.html
Labels: bug, enhancement, frontend

#238 Separate gates logo to sponsored by column
  takwimu/templates/takwimu/_includes/footer.html
  takwimu/templates/takwimu/_includes/navbar/about.html
Labels: bug, enhancement, frontend

#236 improve topic/service nav button
  .gitignore
  takwimu/static/css/takwimu.scss
  takwimu/templates/takwimu/_includes/profile/hero.html
  takwimu/templates/takwimu/_includes/sections/support-services/tabs.html
Labels: bug, frontend

#202 Add Terms and Privacy section
  requirements.txt
  takwimu/migrations/0025_legalnoticesetting.py
  takwimu/migrations/0026_auto_20180723_1557.py
  takwimu/migrations/0027_merge.py
  takwimu/migrations/0028_merge.py
  takwimu/models/dashboard.py
  takwimu/templates/takwimu/_includes/footer.html
  takwimu/templates/takwimu/about/legal.html
  takwimu/templates/takwimu/about/snippets/cookie_policy.md
  takwimu/templates/takwimu/about/snippets/privacy_policy.md
  takwimu/templates/takwimu/about/snippets/terms_of_use.md
  takwimu/templatetags/safemarktags.py
  takwimu/urls.py
  takwimu/views.py
Labels: enhancement, frontend

#180 [Hotfix] Comments Under Topics Nav
  takwimu/templates/takwimu/_includes/profile/topic_detail.html
Labels: frontend, need more info

#250 404 and 500 Pages
  takwimu/templates/404.html
  takwimu/templates/500.html
  takwimu/urls.py
  takwimu/views.py
Labels: backend, enhancement, frontend

#251 Fix faq style
  takwimu/templates/takwimu/_includes/sections/faq/index.html
  takwimu/templates/takwimu/_includes/sections/faq/morebtn_detail.html
  takwimu/templates/takwimu/_includes/sections/faq/tab_detail.html
Labels: bug, frontend

#246 Add subnational boundaries
  takwimu/settings.py
  takwimu/sql/crop_production_index.sql
  takwimu/sql/gdp_in_billions_of_usd.sql
  takwimu/sql/gni_year.sql
  takwimu/sql/hd_index.sql
  takwimu/sql/hiv_prevalence.sql
  takwimu/sql/landscape.sql
  takwimu/sql/life_expectancy_year.sql
  takwimu/sql/literacy.sql
  takwimu/sql/population.sql
  takwimu/sql/wazimap_geography.sql
  takwimu/static/geo/country.geojson
  takwimu/static/geo/country.topojson
  takwimu/static/geo/level1.topojson
Labels: backend, enhancement

#253 add a country map section in profile details that directs to analysis
  takwimu/templates/homepage.html
  takwimu/templates/profile/profile_detail.html
  takwimu/templates/takwimu/_includes/profile/country_section.html
Labels: enhancement, frontend

#237 Improve the carousel box on the home page
  takwimu/static/css/takwimu.scss
  takwimu/static/img/icons/button-arrow.svg
  takwimu/templates/takwimu/_includes/homepage/hero.html
  takwimu/templates/takwimu/_includes/homepage/hero_detail.html
Labels: bug, enhancement

#241 Fix profile content
  takwimu/static/css/takwimu.scss
  takwimu/templates/takwimu/_includes/profile/sections_list.html
  takwimu/templates/takwimu/_includes/profile/sections_list_detail.html
  takwimu/templates/takwimu/profile_page.html
Labels: bug, enhancement, frontend

#260 Change logo order
  takwimu/templates/takwimu/_includes/footer.html
  takwimu/templates/takwimu/_includes/navbar/about.html
Labels: bug, enhancement, frontend

#229 Style TOC profile
  takwimu/static/img/icons/add.svg
  takwimu/static/img/icons/minus.svg
  takwimu/templates/takwimu/_includes/profile/country_selector.html
  takwimu/templates/takwimu/_includes/profile/toc_detail.html
Labels: bug, enhancement, frontend

#244 Adding demographics at National and SubNational Levels
  takwimu/profiles/census.py
  takwimu/sql/population_residence.sql
  takwimu/sql/population_sex.sql
  takwimu/sql/wazimap_geography.sql
  takwimu/static/geo/level1.topojson
  takwimu/tables.py
  takwimu/templates/profile/profile_detail.html
Labels: backend, enhancement

#262 Add community link to Support settings
  takwimu/fixtures/supportsetting.json
  takwimu/migrations/0030_supportsetting_community.py
  takwimu/models/dashboard.py
  takwimu/templates/takwimu/_includes/sections/updates.html
Labels: backend, bug, frontend

#275 Fixes "Link to community forum broken"
  takwimu/templates/takwimu/_includes/navbar/support_services.html
Labels: bug, frontend

#269 rearrange logo in partnership section
  takwimu/templates/takwimu/_includes/partners.html
Labels: bug, frontend

#278 Fix title line break
  takwimu/templates/takwimu/_includes/sections/support-services/tabs.html
Labels: bug, enhancement, frontend

#254 Improve update section
  takwimu/static/img/icons/chat.svg
  takwimu/static/img/icons/wave.svg
  takwimu/templates/takwimu/_includes/sections/stories/index.html
  takwimu/templates/takwimu/_includes/sections/updates.html
Labels: bug, enhancement, frontend

#281 Fix SQL Files
  takwimu/sql/crop_production_year.sql
  takwimu/sql/gdp_year.sql
  takwimu/sql/gni_year.sql
  takwimu/sql/hd_landscape.sql
  takwimu/sql/hiv_prevalence_year.sql
  takwimu/sql/life_expectancy_year.sql
  takwimu/sql/literacy.sql
  takwimu/sql/population_residence.sql
  takwimu/sql/population_sex.sql
  takwimu/sql/population_year.sql
  takwimu/sql/rank_year.sql
  takwimu/sql/wazimap_geography.sql
Labels: backend, bug

#261 Add privacy policy and terms of use
  takwimu/templates/takwimu/about/legal.html
  takwimu/templates/takwimu/about/snippets/cookie_policy.md
  takwimu/templates/takwimu/about/snippets/privacy_policy.md
  takwimu/templates/takwimu/about/snippets/terms_of_use.md
Labels: enhancement, frontend

#279 Open Zendesk Ticket from Enquiry Form
  takwimu/forms.py
  takwimu/settings.py
  takwimu/templates/takwimu/about/support_services.html
  takwimu/views.py
Labels: bug, frontend

#277 Defining support services in Settings
  takwimu/context_processors.py
  takwimu/fixtures/services.json
  takwimu/migrations/0031_supportservicessetting.py
  takwimu/migrations/0032_merge.py
  takwimu/migrations/0033_auto_20180730_1600.py
  takwimu/models/dashboard.py
  takwimu/templates/takwimu/_includes/navbar/support_services.html
  takwimu/templates/takwimu/_includes/sections/support-services/tabs.html
  takwimu/templates/takwimu/about/support_services.html
  takwimu/views.py
  takwimu/wagtail_hooks.py
Labels: backend, enhancement, frontend

#286 improve service button styling
  takwimu/templates/takwimu/_includes/sections/support-services/button.html
Labels: bug, frontend

#284 improve footer style
  takwimu/static/img/logos/ap-footer-white.png
  takwimu/templates/takwimu/_includes/footer.html
Labels: bug, frontend

#282 Fix/explore by topic
  takwimu/context_processors.py
  takwimu/templates/takwimu/_includes/sections/explore/_index.html
  takwimu/templates/takwimu/_includes/sections/explore/topics.html
Labels: backend, bug, enhancement, frontend

#288 Add Elections Data
  takwimu/profiles/census.py
  takwimu/sql/registered_accredited_voters.sql
  takwimu/sql/valid_invalid_votes.sql
  takwimu/sql/votes_per_candidate.sql
  takwimu/tables.py
  takwimu/templates/profile/profile_detail.html
Labels: backend, enhancement

#257 improve country profile hero styling
  takwimu/static/img/icons/icon-download.svg
  takwimu/static/img/icons/toc-menu.svg
  takwimu/templates/homepage.html
  takwimu/templates/takwimu/_includes/profile/country_selector.html
  takwimu/templates/takwimu/_includes/profile/hero.html
Labels: bug, frontend
