Repository TakwimuAfrica/Takwimu, pull requests merged in 2018-10, with the labels that each got.

#413 [Hotfix] Ignore any found boto.cfg file
  .travis.yml
Labels: bug

#414 [Hotfix] Remove /etc/boto.cfg file
  .travis.yml
Labels: bug

#393 Style indicators dataview
  takwimu/static/css/takwimu.scss
  takwimu/templates/takwimu/_includes/dataview/code.html
  takwimu/templates/takwimu/_includes/dataview/document.html
  takwimu/templates/takwimu/_includes/dataview/embed.html
  takwimu/templates/takwimu/_includes/dataview/entity_detail.html
  takwimu/templates/takwimu/_includes/dataview/indicator.html
  takwimu/templates/takwimu/_includes/profile/topic_detail.html
Labels: enhancement, frontend

#394 Add pagination for indicators in topic
  README.md
  docker-compose.yml
  takwimu/settings.py
  takwimu/static/css/takwimu.scss
  takwimu/templates/takwimu/_includes/profile/sections_list.html
  takwimu/templates/takwimu/_includes/profile/topic_detail.html
  takwimu/templates/takwimu/_includes/sections/updates.html
  takwimu/templates/takwimu/_layouts/_base.html
  takwimu/templates/takwimu/_layouts/page.html
  takwimu/templates/takwimu/profile_page.html
Labels: frontend

#397 Add anchors support for header tags
  takwimu/templates/takwimu/_includes/profile/topic_detail.html
  takwimu/templates/takwimu/_layouts/_base.html
Labels: enhancement, frontend

#418 Enable ethiopia
  takwimu/templates/takwimu/_includes/sections/explore/countries.html
Labels: backend, enhancement, frontend

#408 Improve Countries Dropdown Responsiveness
  takwimu/context_processors.py
  takwimu/settings.py
  takwimu/static/css/takwimu.scss
  takwimu/templates/takwimu/_includes/navbar/_dropdown.html
  takwimu/templates/takwimu/_includes/navbar/_index.html
  takwimu/templates/takwimu/_includes/navbar/profiles.html
  takwimu/templates/takwimu/_includes/profile/country_selector.html
  takwimu/templates/takwimu/_includes/profile/hero.html
  takwimu/templates/takwimu/_includes/sections/explore/countries.html
  takwimu/templates/takwimu/profile_page.html
Labels: enhancement, frontend

#417 Feature South Africa
  takwimu/profiles/census.py
  takwimu/sql/causes_of_death_over_five.sql
  takwimu/sql/causes_of_death_under_five.sql
  takwimu/sql/child_births.sql
  takwimu/sql/child_births_by_size.sql
  takwimu/sql/child_births_with_low_birth_weights.sql
  takwimu/sql/child_births_with_reported_birth_weights.sql
  takwimu/sql/donor.sql
  takwimu/sql/donor_funded_programmes.sql
  takwimu/sql/employment_activity_status_sex.sql
  takwimu/sql/fgm_prevalence.sql
  takwimu/sql/food_production.sql
  takwimu/sql/government_funding.sql
  takwimu/sql/health_centers.sql
  takwimu/sql/health_centers_ownership.sql
  takwimu/sql/health_workers.sql
  takwimu/sql/hiv_health_centers.sql
  takwimu/sql/inpatient_diagnosis_over_five.sql
  takwimu/sql/inpatient_diagnosis_under_five.sql
  takwimu/sql/method_sex.sql
  takwimu/sql/officialemploymentstatus.sql
  takwimu/sql/outpatient_diagnosis_over_five.sql
  takwimu/sql/outpatient_diagnosis_under_five.sql
  takwimu/sql/population_residence.sql
  takwimu/sql/population_sex.sql
  takwimu/sql/poverty_age_residence.sql
  takwimu/sql/registered_accredited_voters.sql
  takwimu/sql/residence_poverty_type.sql
  takwimu/sql/seized_firearms.sql
  takwimu/sql/valid_invalid_votes.sql
  takwimu/sql/votes_per_candidate.sql
  takwimu/sql/wazimap_geography.sql
  takwimu/static/geo/country.geojson
  takwimu/static/geo/country.topojson
  takwimu/static/geo/level1.topojson
  takwimu/static/img/maps/ethiopia.svg
  takwimu/static/img/maps/ethopia.svg
  takwimu/tables.py
  takwimu/templates/homepage.html
  takwimu/templates/profile/profile_detail_base.html
  takwimu/templates/profile/profile_detail_takwimu.html
  takwimu/templatetags/geotags.py
Labels: backend, data, enhancement

#419 Enable South Africa
  takwimu/context_processors.py
Labels: backend, enhancement, frontend

#421 Bandage for Requests/Urllib3 incompatiblity
  .travis.yml
  requirements.txt
Labels: backend, bug

#425 Add One Click Country Profile Publishing
  takwimu/context_processors.py
  takwimu/migrations/0040_countrypublishsetting.py
  takwimu/models/__init__.py
  takwimu/models/dashboard.py
Labels: backend, enhancement

#428 [Feature] Use database caching instead of Redis
  docker-compose.yml
  docker-entrypoint.sh
  takwimu/settings.py
Labels: backend, enhancement
