Repository TakwimuAfrica/Takwimu, pull requests merged in 2018-11, with the labels that each got.

#429 Fix Trending Stories
  takwimu/context_processors.py
  takwimu/utils/medium_models.py
Labels: bug

#427 Improve search
  requirements.txt
  takwimu/management/commands/update_topics_index.py
  takwimu/search/__init__.py
  takwimu/search/takwimu_search.py
  takwimu/search/utils.py
  takwimu/settings.py
  takwimu/signals.py
  takwimu/templates/takwimu/_includes/search/_popover.html
  takwimu/templates/takwimu/_includes/search/countries.html
  takwimu/templates/takwimu/_includes/search/index.html
  takwimu/templates/takwimu/_includes/search/sidebar.html
  takwimu/templates/takwimu/_includes/search/table.html
  takwimu/templates/takwimu/_includes/search/topic.html
  takwimu/views.py
Labels: enhancement

#430 Replace wagtail indexing with custom indexing
  docker-entrypoint.sh
Labels: backend, bug

#431 [#161743178] Fix elasticsearch aws auth
  takwimu/search/takwimu_search.py
Labels: bug

#434 [SEARCH] Improve search query optimization
  takwimu/search/takwimu_search.py
  takwimu/templates/takwimu/_includes/search/sidebar.html
  takwimu/views.py
Labels: backend, bug, enhancement

#435 Fix country flag issue
  takwimu/templates/takwimu/_includes/sections/explore/topics.html
Labels: bug

#436 162008192 Multi Field Search Support
  takwimu/management/commands/update_topics_index.py
  takwimu/search/takwimu_search.py
  takwimu/search/utils.py
  takwimu/settings.py
  takwimu/signals.py
  takwimu/templates/takwimu/_includes/search/table.html
Labels: backend, enhancement

#433 Revamp SDGs
  takwimu/context_processors.py
  takwimu/models/dashboard.py
  takwimu/sdg.py
  takwimu/settings.py
  takwimu/static/css/takwimu.scss
  takwimu/templates/takwimu/_includes/navbar/_index.html
  takwimu/templates/takwimu/_includes/navbar/topics.html
  takwimu/templates/takwimu/_includes/sections/sdg/_collapsed.html
  takwimu/templates/takwimu/_includes/sections/sdg/index.html
  takwimu/templates/takwimu/_layouts/page.html
  takwimu/templates/takwimu/sdg_topic_page.html
  takwimu/templates/takwimu/topic_page.html
  takwimu/views.py
Labels: backend

#437 [Hotfix] Add missing migration [#162115012]
  takwimu/migrations/0043_topicblock_widget_sdg.py
Labels: backend, bug

#438 Make Homepage Carousel Autoplay [161713298]
  takwimu/templates/takwimu/_includes/homepage/hero.html
Labels: enhancement, frontend

#439 Fix Logos on Navbar About Dropdown Menu [161713150]
  takwimu/static/css/takwimu.scss
  takwimu/templates/takwimu/_includes/navbar/about.html
Labels: bug, frontend

#442 Downgrade bootstrap to v4.1.1 [162216054]
  takwimu/templates/takwimu/_layouts/_base.html
Labels: bug

#443 Fix Embedded HURUmap Widget White Space Issues [#162261247]
  takwimu/templates/takwimu/_includes/dataview/hurumap.html
Labels: bug, enhancement

#444 Fix Partners Logos [161713150]
  takwimu/static/css/takwimu.scss
  takwimu/templates/takwimu/_includes/footer.html
  takwimu/templates/takwimu/_includes/navbar/about.html
Labels: bug, enhancement
