Repository TakwimuAfrica/Takwimu, pull requests merged in 2018-06, with the labels that each got.

#65 Add icons for social media links in footer nav
  takwimu/templates/takwimu/_includes/footer.html
Labels: enhancement

#108 Rename country reports to be country profiles
  takwimu/feed.py
  takwimu/templates/homepage.html
  takwimu/templates/takwimu/_includes/footer.html
  takwimu/templates/takwimu/_includes/header/report.html
  takwimu/templates/takwimu/_includes/navbar/_dropdown.html
  takwimu/templates/takwimu/_includes/navbar/_index.html
  takwimu/templates/takwimu/_includes/navbar/profiles.html
  takwimu/templates/takwimu/_includes/profile/country_selector.html
  takwimu/templates/takwimu/_includes/profile/section_topics.html
  takwimu/templates/takwimu/_includes/profile/sections_list.html
  takwimu/templates/takwimu/_includes/profile/sections_list_detail.html
  takwimu/templates/takwimu/_includes/report/sections_list.html
  takwimu/templates/takwimu/_includes/sections/explore/countries.html
  takwimu/templates/takwimu/profile_page.html
  takwimu/templates/takwimu/profile_section_page.html
  takwimu/templates/takwimu/report_section_page.html
  takwimu/views.py
Labels: enhancement

#106 Update feature country dropdown
  DATA.md
  takwimu/templates/takwimu/_includes/profile/country_selector.html
  takwimu/templates/takwimu/_layouts/_base.html
Labels: design, enhancement

#113 Implement Data Services page
  takwimu/static/css/takwimu.scss
  takwimu/templates/blocks/partners.html
  takwimu/templates/takwimu/_includes/navbar/_index.html
  takwimu/templates/takwimu/_includes/partners.html
  takwimu/templates/takwimu/_includes/sections/priority/citizens.html
  takwimu/templates/takwimu/_includes/sections/priority/donor.html
  takwimu/templates/takwimu/_includes/sections/priority/government.html
  takwimu/templates/takwimu/_includes/sections/priority/index.html
  takwimu/templates/takwimu/_includes/sections/priority/media.html
  takwimu/templates/takwimu/_includes/sections/priority/ngo.html
  takwimu/templates/takwimu/_includes/sections/priority/social.html
  takwimu/templates/takwimu/about/data-services.html
Labels: design
