Repository TakwimuAfrica/Takwimu, pull requests merged in 2018-09, with the labels that each got.

#356 Add Elasticseach Documentation
  README.md
Labels: bug

#348 Remove community forum link
  takwimu/templates/takwimu/_includes/navbar/support_services.html
Labels: enhancement, frontend

#360 Fixing Nigeria Population
  takwimu/profiles/census.py
  takwimu/sql/population_residence.sql
  takwimu/templates/profile/profile_detail.html
Labels: backend, data

#351 Nigeria Health Data - Number of Births
  takwimu/profiles/census.py
  takwimu/sql/child_births.sql
  takwimu/sql/child_births_by_size.sql
  takwimu/sql/child_births_with_low_birth_weights.sql
  takwimu/sql/child_births_with_reported_birth_weights.sql
  takwimu/tables.py
  takwimu/templates/profile/profile_detail.html
Labels: data, enhancement

#362 Profile Comparison
  takwimu/templates/profile/head2head.html
  takwimu/templates/profile/profile_detail.html
Labels: enhancement, frontend

#366 Exclude topics from unpublished pages
  takwimu/context_processors.py
Labels: backend, bug

#368 Add missing Overview section & improve traversal in Explore by Topic
  takwimu/context_processors.py
Labels: backend, bug

#369 Inform the site visitor charts/statistics are interactive
  takwimu/templates/profile/profile_detail.html
Labels: enhancement, frontend

#367 [WIP] Add linkedin link in support and service tab
  takwimu/templates/takwimu/_includes/navbar/support_services.html
Labels: bug

#363 Geo choices as countries
  takwimu/models/dashboard.py
Labels: backend, bug, enhancement

#364 Force pip to install wazimap from Github
  requirements.txt
Labels: backend, bug

#350 Add search results page with a sidebar filter
  requirements.txt
  takwimu/templates/search_results.html
  takwimu/templates/takwimu/_includes/search/_popover.html
  takwimu/templates/takwimu/_includes/search/countries.html
  takwimu/templates/takwimu/_includes/search/index.html
  takwimu/templates/takwimu/_includes/search/pagination.html
  takwimu/templates/takwimu/_includes/search/sidebar.html
  takwimu/templates/takwimu/_includes/search/table.html
  takwimu/templates/takwimu/_includes/search/topic.html
  takwimu/templates/takwimu/_layouts/_base.html
Labels: frontend

#370 Remove "add to collection" button
  takwimu/templates/takwimu/_includes/search/table.html
Labels: enhancement, frontend

#373 'Country Overview' topic was missing from the results
  takwimu/views.py
Labels: backend, bug

#357 Add SDG Data
  takwimu/profiles/takwimu.py
  takwimu/sdg.py
  takwimu/static/js/profile_map.js
  takwimu/templates/profile/profile_detail.html
  takwimu/templates/profile/profile_detail_base.html
  takwimu/templates/profile/profile_detail_sdg.html
  takwimu/templates/profile/profile_detail_takwimu.html
  takwimu/templatetags/geotags.py
  takwimu/urls.py
  takwimu/views.py
Labels: backend, data, enhancement, frontend

#102 Add search takwimu box on the navbar
  takwimu/templates/search_results.html
  takwimu/templates/takwimu/_includes/navbar/_index.html
  takwimu/templates/takwimu/_includes/navbar/search.html
  takwimu/templates/takwimu/_includes/search/sidebar.html
  takwimu/templates/takwimu/_layouts/_base.html
Labels: enhancement, frontend

#375 Update to latest HURUmap
  requirements.txt
  takwimu/settings.py
  takwimu/templates/takwimu/_includes/homepage/carousel_item_detail.html
  takwimu/urls.py
Labels: backend, enhancement

#377 Rename About Us link to About
  takwimu/templates/takwimu/_includes/navbar/_index.html
Labels: bug, frontend

#374 Search filter
  takwimu/static/css/takwimu.scss
  takwimu/templates/search_results.html
  takwimu/templates/takwimu/_includes/search/_popover.html
  takwimu/templates/takwimu/_includes/search/countries.html
  takwimu/templates/takwimu/_includes/search/index.html
  takwimu/templates/takwimu/_includes/search/pagination.html
  takwimu/templates/takwimu/_includes/search/sidebar.html
  takwimu/templates/takwimu/_includes/search/table.html
  takwimu/templates/takwimu/_includes/search/topic.html
  takwimu/templates/takwimu/_layouts/_base.html
Labels: enhancement, frontend

#378 Improve search
  takwimu/static/css/takwimu.scss
  takwimu/templates/takwimu/_includes/search/_popover.html
Labels: enhancement, frontend

#379 Remove duplicated javascript body includes
  takwimu/templates/profile/profile_detail_base.html
Labels: backend, bug

#380 Initial implementation of HURUmap widget
  takwimu/models/dashboard.py
  takwimu/templates/takwimu/_includes/dataview/hurumap.html
Labels: backend, data, frontend

#383 [Hotfix] Fixes Census Year & UI
  takwimu/templates/profile/profile_detail_takwimu.html
  takwimu/templatetags/geotags.py
Labels: backend, bug, data

#382 [Hotfix] HURUmap Data
  takwimu/models/dashboard.py
  takwimu/profiles/census.py
  takwimu/sql/highest_education_level_reached.sql
  takwimu/sql/school_attendance_sex.sql
  takwimu/tables.py
  takwimu/templates/profile/profile_detail_takwimu.html
Labels: backend, data

#385 Add countries geo map icons
  takwimu/static/img/maps/burkina-faso.svg
  takwimu/static/img/maps/drc.svg
  takwimu/static/img/maps/ethopia.svg
  takwimu/static/img/maps/kenya.svg
  takwimu/static/img/maps/south-africa.svg
  takwimu/static/img/maps/uganda.svg
  takwimu/static/img/maps/zambia.svg
Labels: frontend

#386 Hotfix/more data
  takwimu/models/dashboard.py
  takwimu/profiles/census.py
  takwimu/sql/donor.sql
  takwimu/sql/fgm_prevalence.sql
  takwimu/sql/poverty_age_residence.sql
  takwimu/sql/residence_poverty_type.sql
  takwimu/sql/seized_firearms.sql
  takwimu/tables.py
  takwimu/templates/profile/profile_detail_takwimu.html
Labels: backend, data, enhancement

#389 Give each HURUmap Widget unique id
  takwimu/templates/takwimu/_includes/dataview/hurumap.html
  takwimu/templatetags/datastructuretags.py
Labels: backend, bug, data

#390 Fix/hurumap widget height
  takwimu/models/dashboard.py
  takwimu/templates/takwimu/_includes/dataview/hurumap.html
Labels: backend, bug, enhancement, frontend

#391 Hotfix/data kenya v2
  takwimu/models/dashboard.py
  takwimu/profiles/census.py
  takwimu/sql/donor_funded_programmes.sql
  takwimu/sql/government_funding.sql
  takwimu/sql/health_centers.sql
  takwimu/tables.py
  takwimu/templates/profile/profile_detail_takwimu.html
Labels: backend, data, enhancement

#392 Add subtitle and fix source on HURUmap Widget
  takwimu/models/dashboard.py
  takwimu/templates/takwimu/_includes/dataview/hurumap.html
Labels: backend, bug, data, enhancement

#388 Make Homepage Mobile Responsive
  .gitignore
  Makefile
  README.md
  takwimu/fixtures/testimonials.json
  takwimu/static/css/takwimu.scss
  takwimu/static/img/icons/arrow-1.png
  takwimu/static/img/icons/arrow-1.svg
  takwimu/static/img/icons/arrow-1@2x.png
  takwimu/static/img/icons/arrow-1@3x.png
  takwimu/static/img/icons/arrow-2.png
  takwimu/static/img/icons/arrow-2.svg
  takwimu/static/img/icons/arrow-2@2x.png
  takwimu/static/img/icons/arrow-2@3x.png
  takwimu/static/img/screens/TAKWIMU_tse8BlL.width-800.png
  takwimu/static/img/screens/compile.png
  takwimu/static/img/screens/compile@2x.png
  takwimu/static/img/screens/compile@3x.png
  takwimu/static/img/screens/contribute.png
  takwimu/static/img/screens/contribute@2x.png
  takwimu/static/img/screens/contribute@3x.png
  takwimu/static/img/screens/use-and-share.png
  takwimu/static/img/screens/use-and-share2x.width-800.png
  takwimu/static/img/screens/use-and-share@2x.png
  takwimu/static/img/screens/use-and-share@3x.png
  takwimu/templates/takwimu/_includes/footer.html
  takwimu/templates/takwimu/_includes/homepage/hero.html
  takwimu/templates/takwimu/_includes/navbar/_dropdown.html
  takwimu/templates/takwimu/_includes/navbar/_index.html
  takwimu/templates/takwimu/_includes/navbar/about.html
  takwimu/templates/takwimu/_includes/navbar/profiles.html
  takwimu/templates/takwimu/_includes/navbar/support_services.html
  takwimu/templates/takwimu/_includes/navbar/topics.html
  takwimu/templates/takwimu/_includes/profile/toc_detail.html
  takwimu/templates/takwimu/_includes/search/table.html
  takwimu/templates/takwimu/_includes/sections/faq/morebtn_detail.html
  takwimu/templates/takwimu/_includes/sections/how-it-works/index.html
  takwimu/templates/takwimu/_includes/sections/how-it-works/nav_detail.html
  takwimu/templates/takwimu/_includes/sections/stories/index.html
  takwimu/templates/takwimu/_includes/sections/stories/story_detail.html
  takwimu/templates/takwimu/_includes/sections/support-services/button.html
  takwimu/templates/takwimu/_includes/sections/support-services/tabs.html
  takwimu/templates/takwimu/_includes/sections/testimonials.html
  takwimu/templates/takwimu/_includes/sections/updates.html
Labels: enhancement, frontend

#398 Improvement around HURUmap integration
  takwimu/models/dashboard.py
  takwimu/profiles/census.py
  takwimu/sql/donor.sql
  takwimu/sql/donor_funded_programmes.sql
  takwimu/sql/poverty_age_residence.sql
  takwimu/templates/profile/profile_detail_base.html
  takwimu/templates/takwimu/_includes/dataview/hurumap.html
  takwimu/templates/takwimu/_includes/dataview/indicator.html
Labels: backend, bug, data

#402 [Hotfix] Fix census and migrations
  takwimu/migrations/0039_auto_20180925_1833.py
  takwimu/profiles/census.py
Labels: backend, bug, data

#401 Style show more button in profile page
  takwimu/templates/takwimu/_includes/profile/topic_detail.html
Labels: enhancement, frontend

#407 Fix HURUmap widget iframe id and message handling
  takwimu/templates/takwimu/_includes/dataview/hurumap.html
Labels: bug, data, frontend

#400 Style left menu country profile
  takwimu/static/css/takwimu.scss
  takwimu/templates/takwimu/_includes/profile/topic_detail.html
Labels: enhancement, frontend

#409 Fix multiple HURUmap widgets on a single page
  takwimu/templates/takwimu/_includes/dataview/hurumap.html
Labels: bug, frontend

#361 SDG landing page
  takwimu/fixtures/sdg.json
  takwimu/static/css/takwimu.scss
  takwimu/static/img/icons/agriculture.svg
  takwimu/static/img/icons/education.svg
  takwimu/static/img/icons/financial-inclusion.svg
  takwimu/static/img/icons/health.svg
  takwimu/static/img/icons/icon-tick.svg
  takwimu/static/img/icons/sdg/e-sdg-goals-icons-individual-rgb-01@2x.png
  takwimu/static/img/icons/sdg/e-sdg-goals-icons-individual-rgb-02@2x.png
  takwimu/static/img/icons/sdg/e-sdg-goals-icons-individual-rgb-03@2x.png
  takwimu/static/img/icons/sdg/e-sdg-goals-icons-individual-rgb-04@2x.png
  takwimu/static/img/icons/sdg/e-sdg-goals-icons-individual-rgb-05@2x.png
  takwimu/static/img/icons/sdg/e-sdg-goals-icons-individual-rgb-06@2x.png
  takwimu/static/img/icons/sdg/e-sdg-goals-icons-individual-rgb-07@2x.png
  takwimu/static/img/icons/sdg/e-sdg-goals-icons-individual-rgb-08@2x.png
  takwimu/static/img/icons/sdg/e-sdg-goals-icons-individual-rgb-09@2x.png
  takwimu/static/img/icons/sdg/e-sdg-goals-icons-individual-rgb-10@2x.png
  takwimu/static/img/icons/sdg/e-sdg-goals-icons-individual-rgb-11@2x.png
  takwimu/static/img/icons/sdg/e-sdg-goals-icons-individual-rgb-12@2x.png
  takwimu/static/img/icons/sdg/e-sdg-goals-icons-individual-rgb-13@2x.png
  takwimu/static/img/icons/sdg/e-sdg-goals-icons-individual-rgb-14@2x.png
  takwimu/static/img/icons/sdg/e-sdg-goals-icons-individual-rgb-15@2x.png
  takwimu/static/img/icons/sdg/e-sdg-goals-icons-individual-rgb-16@2x.png
  takwimu/static/img/icons/sdg/e-sdg-goals-icons-individual-rgb-17@2x.png
  takwimu/templates/takwimu/_includes/sections/sdg/_collapsed.html
  takwimu/templates/takwimu/_includes/sections/sdg/index.html
  takwimu/templates/takwimu/_includes/sections/sdg/nav.html
  takwimu/templates/takwimu/_includes/sections/sdg/popover.html
  takwimu/templates/takwimu/_layouts/_base.html
  takwimu/templates/takwimu/sdg_topic_page.html
  takwimu/urls.py
  takwimu/views.py
Labels: enhancement, frontend

#411 Add Sources and Publication Year to Visualisations
  takwimu/profiles/census.py
  takwimu/sql/highest_education_level_reached.sql
  takwimu/sql/school_attendance_sex.sql
  takwimu/templates/profile/profile_detail_takwimu.html
Labels: backend, data, enhancement

#412 Enable Kenya
  takwimu/templates/takwimu/_includes/sections/explore/countries.html
Labels: backend, enhancement, frontend
