Repository TakwimuAfrica/Takwimu, pull requests merged in 2019-05, with the labels that each got.

#516 [Staging] Add Usersnap for UAT
  takwimu/templates/profile/profile_detail_base.html
  takwimu/templates/takwimu/_layouts/_base.html
Labels: frontend

#517 [Staging] Analysis Hero
  takwimu/takwimu_ui/src/assets/images/profile-hero-line.png
  takwimu/takwimu_ui/src/components/AnalysisContent/index.js
Labels: bug, design, frontend

#519 [Staging] Fix data container action buttons and embed code
  takwimu/takwimu_ui/src/components/DataContainer/DataActions.js
  takwimu/takwimu_ui/src/components/DataContainer/IFrame.js
Labels: bug, design, frontend

#520 [Staging] Fix flourish visuals
  takwimu/takwimu_ui/src/components/AnalysisContent/index.js
Labels: bug, frontend

#514 [Staging] Index HURUmap Visualizations
  Dockerfile
  requirements.txt
  takwimu/management/commands/update_topics_index.py
  takwimu/search/takwimu_search.py
  takwimu/settings.py
  takwimu/urls.py
  takwimu/views.py
Labels: backend, data, enhancement

#505 [Staging] Search, Search Result List and Navigation
  docker-compose.yml
  takwimu/management/commands/update_topics_index.py
  takwimu/migrations/0056_auto_20190503_1128.py
  takwimu/models/dashboard.py
  takwimu/search/takwimu_search.py
  takwimu/settings.py
  takwimu/static/css/takwimu.scss
  takwimu/takwimu_ui/public/index.html
  takwimu/takwimu_ui/src/components/Navigation/SearchDrawer.js
  takwimu/takwimu_ui/src/components/Navigation/index.js
  takwimu/takwimu_ui/src/components/SearchResults/SearchInput.js
  takwimu/takwimu_ui/src/components/SearchResults/SearchResultItem.js
  takwimu/takwimu_ui/src/components/SearchResults/SearchResultsContainer.js
  takwimu/takwimu_ui/src/components/SearchResults/index.js
  takwimu/takwimu_ui/src/index.js
  takwimu/takwimu_ui/yarn.lock
  takwimu/templates/search_results.html
  takwimu/templates/takwimu/search_page.html
  takwimu/urls.py
  takwimu/views.py
Labels: backend, data, design, enhancement, frontend

#522 More fixes UI/UX review
  takwimu/static/css/takwimu.scss
  takwimu/takwimu_ui/src/components/AboutUsContent/index.js
  takwimu/takwimu_ui/src/components/LatestNewsStories/StoryCard.js
  takwimu/takwimu_ui/src/components/Navigation/DropDownButton.js
  takwimu/takwimu_ui/src/components/Next/About.js
  takwimu/takwimu_ui/src/components/ProfileDetail/index.js
  takwimu/takwimu_ui/src/components/Section.js
  takwimu/takwimu_ui/src/components/TableOfContent.js
  takwimu/takwimu_ui/src/pages/AboutUs.js
Labels: frontend

#511 [Staging] Baseline
  takwimu/management/commands/update_topics_index.py
  takwimu/migrations/0057_baseline.py
  takwimu/models/dashboard.py
  takwimu/models/utils/__init__.py
  takwimu/models/utils/search.py
  takwimu/search/__init__.py
  takwimu/search/search.py
  takwimu/search/takwimu_search.py
  takwimu/signals.py
  takwimu/takwimu_ui/public/index.html
  takwimu/takwimu_ui/src/components/AboutUsContent/AboutUsContentNav.js
  takwimu/takwimu_ui/src/components/AboutUsContent/ContentNavigation.js
  takwimu/takwimu_ui/src/components/AboutUsContent/index.js
  takwimu/takwimu_ui/src/components/AnalysisContent/Actions.js
  takwimu/takwimu_ui/src/components/AnalysisContent/index.js
  takwimu/takwimu_ui/src/components/CountryContent/Selection.js
  takwimu/takwimu_ui/src/components/CountryContent/index.js
  takwimu/takwimu_ui/src/components/DataContainer/index.js
  takwimu/takwimu_ui/src/components/Faqs/index.js
  takwimu/takwimu_ui/src/components/FeaturedAnalysis/AnalysisList.js
  takwimu/takwimu_ui/src/components/FeaturedAnalysis/CurrentAnalysis.js
  takwimu/takwimu_ui/src/components/FeaturedAnalysis/index.js
  takwimu/takwimu_ui/src/components/FeaturedData.js
  takwimu/takwimu_ui/src/components/Footer/QuickLinks.js
  takwimu/takwimu_ui/src/components/Hero.js
  takwimu/takwimu_ui/src/components/LatestNewsStories/index.js
  takwimu/takwimu_ui/src/components/MakingOfTakwimu.js
  takwimu/takwimu_ui/src/components/Navigation/DropDowns.js
  takwimu/takwimu_ui/src/components/Navigation/index.js
  takwimu/takwimu_ui/src/components/Next/Analysis.js
  takwimu/takwimu_ui/src/components/RelatedContent/Links.js
  takwimu/takwimu_ui/src/components/RelatedContent/index.js
  takwimu/takwimu_ui/src/components/SearchResults/SearchInput.js
  takwimu/takwimu_ui/src/components/SearchResults/SearchResultsContainer.js
  takwimu/takwimu_ui/src/components/SearchResults/index.js
  takwimu/takwimu_ui/src/components/Services.js
  takwimu/takwimu_ui/src/components/WhatCanYouDo.js
  takwimu/takwimu_ui/src/components/WhatYouCanDoWithTakwimu.js
  takwimu/takwimu_ui/src/index.js
  takwimu/takwimu_ui/src/pages/AboutUs.js
  takwimu/takwimu_ui/src/pages/Analysis.js
  takwimu/templates/profile/profile_detail_base.html
  takwimu/templates/takwimu/_layouts/_base.html
  takwimu/templates/takwimu/about_page.html
  takwimu/templates/takwimu/home_page.html
  takwimu/templates/takwimu/profile_page.html
  takwimu/templates/takwimu/profile_section_page.html
  takwimu/templates/takwimu/search_page.html
  takwimu/urls.py
  takwimu/utils/helpers.py
  takwimu/views.py
Labels: backend, enhancement, frontend

#524 [Staging] Fix featured data
  takwimu/static/js/charts.js
  takwimu/takwimu_ui/src/components/DataContainer/FeaturedDataContainer.js
Labels: bug, frontend

#518 [Staging] Fixes: Takwimu UX Review Feedback
  takwimu/static/css/takwimu.scss
  takwimu/takwimu_ui/public/index.html
  takwimu/takwimu_ui/src/Theme.js
  takwimu/takwimu_ui/src/components/AboutUsContent/AboutUsContentNav.js
  takwimu/takwimu_ui/src/components/AboutUsContent/ContentNavigation.js
  takwimu/takwimu_ui/src/components/AboutUsContent/TableOfContent.js
  takwimu/takwimu_ui/src/components/AboutUsContent/index.js
  takwimu/takwimu_ui/src/components/AnalysisContent/Actions.js
  takwimu/takwimu_ui/src/components/AnalysisContent/ContentNavigation.js
  takwimu/takwimu_ui/src/components/AnalysisContent/OtherInfoNav.js
  takwimu/takwimu_ui/src/components/ContentNavigation.js
  takwimu/takwimu_ui/src/components/ContentPage.js
  takwimu/takwimu_ui/src/components/DataContainer/index.js
  takwimu/takwimu_ui/src/components/FeaturedAnalysis/CurrentAnalysis.js
  takwimu/takwimu_ui/src/components/FeaturedAnalysis/index.js
  takwimu/takwimu_ui/src/components/Footer/Initiative.js
  takwimu/takwimu_ui/src/components/Footer/Support.js
  takwimu/takwimu_ui/src/components/Footer/Takwimu.js
  takwimu/takwimu_ui/src/components/LatestNewsStories/StoryCard.js
  takwimu/takwimu_ui/src/components/LatestNewsStories/index.js
  takwimu/takwimu_ui/src/components/MakingOfTakwimu.js
  takwimu/takwimu_ui/src/components/Navigation/DropDownButton.js
  takwimu/takwimu_ui/src/components/Navigation/DropDownContent.js
  takwimu/takwimu_ui/src/components/Navigation/index.js
  takwimu/takwimu_ui/src/components/Next/About.js
  takwimu/takwimu_ui/src/components/ProfileDetail/index.js
  takwimu/takwimu_ui/src/components/SearchResults/SearchResultsContainer.js
  takwimu/takwimu_ui/src/components/SearchResults/index.js
  takwimu/takwimu_ui/src/components/Section.js
  takwimu/takwimu_ui/src/components/TableOfContent.js
  takwimu/takwimu_ui/src/components/WhatYouCanDoWithTakwimu.js
  takwimu/takwimu_ui/src/pages/AboutUs.js
  takwimu/templates/takwimu/about/contact.html
  takwimu/templates/takwimu/about/index.html
  takwimu/templates/takwimu/about/legal.html
  takwimu/templates/takwimu/about/snippets/privacy_policy.md
  takwimu/templates/takwimu/about/snippets/terms_of_use.md
  takwimu/templates/takwimu/about/support_services.html
  takwimu/templates/takwimu/about_page.html
  takwimu/urls.py
  takwimu/views.py
Labels: bug, frontend

#528 [Staging] Add New Favicons
  takwimu/static/img/favicons/android-chrome-144x144.png
  takwimu/static/img/favicons/android-chrome-192x192.png
  takwimu/static/img/favicons/android-chrome-256x256.png
  takwimu/static/img/favicons/apple-touch-icon.png
  takwimu/static/img/favicons/browserconfig.xml
  takwimu/static/img/favicons/favicon-16x16.png
  takwimu/static/img/favicons/favicon-32x32.png
  takwimu/static/img/favicons/favicon.ico
  takwimu/static/img/favicons/mstile-150x150.png
  takwimu/static/img/favicons/safari-pinned-tab.svg
  takwimu/static/img/favicons/site.webmanifest
  takwimu/takwimu_ui/public/favicon.ico
Labels: enhancement, frontend

#529 [Staging] Quick fix for Favicons
  takwimu/takwimu_ui/public/index.html
  takwimu/takwimu_ui/public/static/android-chrome-192x192.png
  takwimu/takwimu_ui/public/static/android-chrome-256x256.png
  takwimu/takwimu_ui/public/static/apple-touch-icon.png
  takwimu/takwimu_ui/public/static/browserconfig.xml
  takwimu/takwimu_ui/public/static/favicon-16x16.png
  takwimu/takwimu_ui/public/static/favicon-32x32.png
  takwimu/takwimu_ui/public/static/favicon.ico
  takwimu/takwimu_ui/public/static/mstile-150x150.png
  takwimu/takwimu_ui/public/static/safari-pinned-tab.svg
  takwimu/takwimu_ui/public/static/site.webmanifest
  takwimu/templates/profile/profile_detail_base.html
  takwimu/templates/takwimu/_layouts/_base.html
Labels: enhancement, frontend

#526 [Staging] Tweet analysis link
  takwimu/takwimu_ui/package.json
  takwimu/takwimu_ui/src/components/AnalysisContent/Actions.js
  takwimu/takwimu_ui/yarn.lock
Labels: design, enhancement, frontend

#527 [Staging] Profile Charts Comparison
  takwimu/profiles/census.py
  takwimu/settings.py
  takwimu/takwimu_ui/src/components/ProfileDetail/index.js
Labels: bug, enhancement

#535 [Staging] Feedback 03
  takwimu/takwimu_ui/src/components/ContentNavigation.js
  takwimu/takwimu_ui/src/components/Navigation/index.js
  takwimu/takwimu_ui/src/components/Next/Card.js
Labels: bug

#530 [Staging] Configurable Indicator Layout
  takwimu/migrations/0059_featured_data_indicator_layout.py
  takwimu/models/dashboard.py
  takwimu/takwimu_ui/src/components/AnalysisContent/index.js
  takwimu/takwimu_ui/src/components/DataContainer/HURUmapContainer.js
  takwimu/takwimu_ui/src/components/DataContainer/IFrame.js
  takwimu/takwimu_ui/src/components/DataContainer/index.js
  takwimu/takwimu_ui/src/components/FeaturedData.js
Labels: backend, bug, data, enhancement, frontend

#532 [Staging] Adding WorldBank data for remaining countries
  takwimu/profiles/census.py
  takwimu/sql/account_ownership.sql
  takwimu/sql/adult_literacy_rate.sql
  takwimu/sql/agricultural_land.sql
  takwimu/sql/births_attended_by_skilled_health_staff.sql
  takwimu/sql/cereal_yield_kg_per_hectare.sql
  takwimu/sql/employment_to_population_ratio.sql
  takwimu/sql/fgm_prevalence.sql
  takwimu/sql/foreign_direct_investment_net_inflows.sql
  takwimu/sql/gdp_per_capita.sql
  takwimu/sql/mobile_phone_subscriptions.sql
  takwimu/sql/prevalence_of_undernourishment.sql
  takwimu/sql/primary_education_completion_rate.sql
  takwimu/sql/primary_school_enrollment.sql
  takwimu/sql/secondary_school_enrollment.sql
  takwimu/sql/tax_as_percentage_of_gdp.sql
  takwimu/sql/total_population.sql
  takwimu/sql/youth_unemployment.sql
  takwimu/tables.py
  takwimu/takwimu_ui/yarn.lock
  takwimu/templates/profile/profile_detail_takwimu.html
Labels: data, enhancement, frontend

#533 [Staging] feature/download flourish visuals
  takwimu/migrations/0060_flourish_visuals.py
  takwimu/models/dashboard.py
  takwimu/renderers.py
  takwimu/takwimu_ui/src/components/DataContainer/FlourishDataContainer.js
  takwimu/takwimu_ui/src/components/DataContainer/HurumapDataContainer.js
  takwimu/takwimu_ui/src/components/DataContainer/index.js
  takwimu/urls.py
  takwimu/views.py
Labels: bug, enhancement

#538 [Staging] Fix Chart Compare Action
  takwimu/templates/data/_base_data.html
  takwimu/urls.py
Labels: bug

#540 [Staging] Contact us page
  takwimu/migrations/0061_contactpage_redesign.py
  takwimu/models/dashboard.py
  takwimu/takwimu_ui/public/index.html
  takwimu/takwimu_ui/src/assets/images/logo-facebook.svg
  takwimu/takwimu_ui/src/assets/images/logo-github.svg
  takwimu/takwimu_ui/src/assets/images/logo-medium.svg
  takwimu/takwimu_ui/src/assets/images/logo-twitter.svg
  takwimu/takwimu_ui/src/components/AboutContent/index.js
  takwimu/takwimu_ui/src/components/ContactContent/ContactContentNav.js
  takwimu/takwimu_ui/src/components/ContactContent/TableOfContent.js
  takwimu/takwimu_ui/src/components/ContactContent/index.js
  takwimu/takwimu_ui/src/components/ContentSection.js
  takwimu/takwimu_ui/src/components/Footer/QuickLinks.js
  takwimu/takwimu_ui/src/components/Navigation/index.js
  takwimu/takwimu_ui/src/components/Next/About.js
  takwimu/takwimu_ui/src/components/Next/Home.js
  takwimu/takwimu_ui/src/index.js
  takwimu/takwimu_ui/src/pages/Contact.js
  takwimu/templates/takwimu/contact_page.html
  takwimu/templates/takwimu/contact_us_page.html
  takwimu/wagtail_hooks.py
Labels: backend, design, enhancement, frontend

#536 [Staging] Data by Topic to Country Analysis Bridge
  takwimu/management/commands/update_topics_index.py
  takwimu/migrations/0062_profiledata.py
  takwimu/models/__init__.py
  takwimu/models/dashboard.py
  takwimu/models/data.py
  takwimu/settings.py
  takwimu/takwimu_ui/src/components/DataContainer/IFrame.js
  takwimu/takwimu_ui/src/components/DataContainer/index.js
  takwimu/templates/profile/profile_detail_sdg.html
  takwimu/templates/profile/profile_detail_takwimu.html
Labels: backend, data, enhancement, frontend

#543 [Staging] [Hotfix] Contact page & Data by Topic page
  takwimu/takwimu_ui/src/components/ProfileDetail/index.js
  takwimu/templates/profile/profile_detail_base.html
  takwimu/templates/takwimu/_layouts/_base.html
  takwimu/templates/takwimu/contact_page.html
Labels: bug, data, frontend

#546 [Staging] Add Flourish widget to FeaturedData
  takwimu/migrations/0063_featureddata_flourish_support.py
  takwimu/models/dashboard.py
Labels: backend, design, enhancement, frontend

#548 [Staging] Feedback 04
  takwimu/migrations/0065_feedback_04.py
  takwimu/models/dashboard.py
  takwimu/renderers.py
  takwimu/takwimu_ui/src/components/AnalysisContent/index.js
  takwimu/takwimu_ui/src/components/AnalysisContent/topics/CarouselTopic.js
  takwimu/takwimu_ui/src/components/ContentNavigation.js
  takwimu/takwimu_ui/src/components/DataContainer/FlourishDataContainer.js
  takwimu/takwimu_ui/src/components/FeaturedAnalysis/AnalysisList.js
  takwimu/takwimu_ui/src/components/FeaturedAnalysis/CurrentAnalysis.js
  takwimu/takwimu_ui/src/components/FeaturedAnalysis/index.js
  takwimu/takwimu_ui/src/components/FeaturedData.js
  takwimu/takwimu_ui/src/components/Footer/QuickLinks.js
  takwimu/takwimu_ui/src/components/Footer/StayInTouch.js
  takwimu/takwimu_ui/src/components/Footer/Title.js
  takwimu/takwimu_ui/src/components/LatestNewsStories/index.js
  takwimu/takwimu_ui/src/components/Navigation/index.js
  takwimu/takwimu_ui/src/components/Next/Contact.js
  takwimu/takwimu_ui/src/components/RichTextSection.js
  takwimu/takwimu_ui/src/components/Services.js
  takwimu/urls.py
  takwimu/utils/helpers.py
  takwimu/views.py
Labels: backend, bug, design, enhancement, frontend

#549 [Staging] Introduce Data by Topic Pages
  takwimu/migrations/0066_databytopicpage.py
  takwimu/models/dashboard.py
  takwimu/takwimu_ui/src/components/Profile/index.js
  takwimu/templates/profile/profile_detail_base.html
  takwimu/views.py
Labels: backend, data, enhancement, frontend

#550 [Staging] Bug data map
  takwimu/fixtures/wazimap.json
  takwimu/sql/wazimap_geography.sql
  takwimu/static/img/logos/takwimu-logo.png
  takwimu/static/js/charts.js
  takwimu/static/js/map_mapit.js
  takwimu/templates/data/_base_data.html
  takwimu/templates/data/data_map.html
Labels: backend, data, enhancement

#545 [Staging] Improve Chart axis labeling
  Dockerfile
  takwimu/settings.py
  takwimu/static/css/takwimu.scss
  takwimu/static/js/charts.js
  takwimu/templates/settings_js.html
Labels: data, design, enhancement, frontend

#553 [Staging] Feedback 05
  takwimu/migrations/0067_hurumapblock_number-stat-type.py
  takwimu/models/dashboard.py
  takwimu/takwimu_ui/src/components/AnalysisContent/Actions.js
  takwimu/takwimu_ui/src/components/AnalysisContent/index.js
  takwimu/takwimu_ui/src/components/AnalysisContent/topics/CarouselTopic.js
  takwimu/takwimu_ui/src/components/DataContainer/EntitiesDataContainer.js
  takwimu/takwimu_ui/src/components/DataContainer/HTMLDataContainer.js
  takwimu/takwimu_ui/src/components/Faqs/Faq.js
  takwimu/takwimu_ui/src/components/Faqs/index.js
  takwimu/takwimu_ui/src/components/FeaturedAnalysis/AnalysisListItem.js
  takwimu/takwimu_ui/src/components/FeaturedAnalysis/CurrentAnalysis.js
  takwimu/takwimu_ui/src/components/Hero.js
  takwimu/takwimu_ui/src/components/LatestNewsStories/index.js
  takwimu/takwimu_ui/src/components/MakingOfTakwimu.js
  takwimu/takwimu_ui/src/components/Navigation/DropDownContent.js
  takwimu/takwimu_ui/src/components/Profile/index.js
  takwimu/takwimu_ui/src/components/RichTextSection.js
  takwimu/takwimu_ui/src/components/SearchResults/SearchResultItem.js
  takwimu/takwimu_ui/src/components/Section.js
  takwimu/takwimu_ui/src/components/Services.js
  takwimu/takwimu_ui/src/components/WhatYouCanDoWithTakwimu.js
  takwimu/takwimu_ui/src/components/core/RichTypography.js
  takwimu/takwimu_ui/src/components/core/index.js
  takwimu/takwimu_ui/src/pages/Contact.js
Labels: backend, bug, data, enhancement, frontend

#554 [Staging] Categorise WorldBank data
  takwimu/profiles/census.py
  takwimu/takwimu_ui/src/components/Profile/Tabs.js
  takwimu/templates/profile/profile_detail_base.html
  takwimu/templates/profile/profile_detail_takwimu.html
Labels: data, enhancement, frontend

#544 [Staging] Share indicator on twitter
  Dockerfile
  takwimu/models/dashboard.py
  takwimu/models/utils/page.py
  takwimu/static/js/charts.js
  takwimu/takwimu_ui/src/common.js
  takwimu/takwimu_ui/src/components/DataContainer/DataActions.js
  takwimu/takwimu_ui/src/components/DataContainer/FlourishDataContainer.js
  takwimu/takwimu_ui/src/components/DataContainer/HurumapDataContainer.js
  takwimu/takwimu_ui/src/components/DataContainer/common.js
  takwimu/takwimu_ui/src/components/DataContainer/index.js
  takwimu/takwimu_ui/src/components/FeaturedData.js
  takwimu/templates/profile/profile_detail_base.html
  takwimu/templates/takwimu/home_page.html
  takwimu/templates/takwimu/profile_page.html
  takwimu/urls.py
  takwimu/utils/image.py
  takwimu/views.py
Labels: enhancement

#557 [Staging] Fix component links
  takwimu/takwimu_ui/public/index.html
  takwimu/takwimu_ui/src/components/FeaturedAnalysis/CurrentAnalysis.js
  takwimu/takwimu_ui/src/components/Next/Home.js
Labels: bug, design, frontend

#559 [Staging] PDF Document Indicator to download document
  takwimu/takwimu_ui/src/components/DataContainer/PDFDataContainer.js
Labels: bug, enhancement, frontend

#563 [Staging] [Hotfix] Preserve ProfileData
  takwimu/management/commands/update_topics_index.py
Labels: bug, data

#562 [Staging] PDF Document Formatting
  takwimu/takwimu_ui/src/components/AnalysisContent/index.js
  takwimu/takwimu_ui/src/components/FeaturedAnalysis/index.js
  takwimu/takwimu_ui/src/components/core/countrify.js
  takwimu/takwimu_ui/src/components/core/index.js
Labels: enhancement, help wanted

#565 [Staging] Fix Featured Data
  takwimu/migrations/0069_featureddata_qualifiers.py
  takwimu/models/dashboard.py
  takwimu/static/css/embedchart.scss
  takwimu/takwimu_ui/src/components/DataContainer/HurumapDataContainer.js
  takwimu/takwimu_ui/src/components/DataContainer/IFrame.js
  takwimu/templates/homepage.html
  takwimu/templates/takwimu/profile_page.html
Labels: backend, data, design, enhancement, frontend

#566 [Staging] [Hotfix] Improve Flourish Widget
  takwimu/migrations/0070_featureddata_flourish_description.py
  takwimu/models/dashboard.py
  takwimu/takwimu_ui/src/components/DataContainer/FlourishDataContainer.js
Labels: backend, bug, design, enhancement, frontend

#567 [Staging] [Hotfix] Image widget
  takwimu/migrations/0071_imagewidget.py
  takwimu/models/dashboard.py
  takwimu/takwimu_ui/src/components/DataContainer/ImageDataContainer.js
  takwimu/takwimu_ui/src/components/DataContainer/index.js
  takwimu/templates/takwimu/_includes/dataview/image.html
Labels: backend, bug, design, enhancement, frontend

#568 [Staging] [Hotfix] Flourish Widget
  takwimu/renderers.py
  takwimu/takwimu_ui/src/components/DataContainer/FlourishDataContainer.js
  takwimu/views.py
Labels: backend, bug, frontend

#570 [Staging] [Hotfix] carousel topic header
  takwimu/takwimu_ui/src/components/AnalysisContent/topics/CarouselTopic.js
Labels: bug, design, enhancement, frontend

#575 [FIX] Flourish widget assets folder support
  takwimu/renderers.py
  takwimu/urls.py
  takwimu/views.py
Labels: bug
