Repository TakwimuAfrica/Takwimu, pull requests merged in 2019-11, with the labels that each got.

#619 Fix chart data & Remove suffix percent for total
  takwimu/profiles/census.py
  takwimu/templates/profile/profile_detail_takwimu.html
Labels: bug

#620 [Hotfix] Update KNBS data links
  takwimu/profiles/census.py
Labels: bug, data

#621 Add 2019 Kenya Census Data
  Makefile
  takwimu/fixtures/wazimap.json
  takwimu/profiles/census.py
  takwimu/settings.py
  takwimu/sql/avg_household_size.sql
  takwimu/sql/households_and_population.sql
  takwimu/sql/population_sex_2019.sql
  takwimu/sql/subcounty_population_sex_2019.sql
  takwimu/sql/wazimap_geography.sql
  takwimu/templates/profile/profile_detail_takwimu.html
Labels: backend, data
