Repository TakwimuAfrica/Takwimu, pull requests merged in 2019-09, with the labels that each got.

#611 MIDDLEWARE Fixes
  Dockerfile
  takwimu/settings.py
Labels: backend, bug

#612 Enable same-origin for HURUmap & Flourish Viz
  takwimu/takwimu_ui/src/components/DataContainer/HurumapDataContainer.js
  takwimu/takwimu_ui/src/components/DataContainer/IFrame.js
  takwimu/takwimu_ui/src/index.js
  takwimu/templates/settings_js.html
  takwimu/views.py
Labels: enhancement

#615 Update wazimap fixtures
  takwimu/fixtures/wazimap.json
  takwimu/sql/population_sex_2011.sql
Labels: backend, bug

#616 Show chart actions on sub-national profile charts
  takwimu/templates/profile/profile_detail_base.html
Labels: bug
