Repository TakwimuAfrica/Takwimu, pull requests merged in 2019-04, with the labels that each got.

#482 [Staging] Update gitignore file
  .gitignore
Labels: bug

#475 [Staging] Featured data
  takwimu/takwimu_ui/public/index.html
  takwimu/takwimu_ui/src/Theme.js
  takwimu/takwimu_ui/src/assets/images/code.svg
  takwimu/takwimu_ui/src/assets/images/compare.svg
  takwimu/takwimu_ui/src/assets/images/download.svg
  takwimu/takwimu_ui/src/assets/images/network-connection.svg
  takwimu/takwimu_ui/src/assets/images/tablet-reader-31.svg
  takwimu/takwimu_ui/src/components/FeaturedData/DataActions.js
  takwimu/takwimu_ui/src/components/FeaturedData/DataContainer.js
  takwimu/takwimu_ui/src/components/FeaturedData/data.js
  takwimu/takwimu_ui/src/components/FeaturedData/index.js
  takwimu/takwimu_ui/src/index.js
Labels: enhancement, frontend

#488 [Staging] Create hero component
  takwimu/takwimu_ui/public/index.html
  takwimu/takwimu_ui/src/Theme.js
  takwimu/takwimu_ui/src/assets/images/africanparliament.jpg
  takwimu/takwimu_ui/src/assets/images/africanparliament@2x.jpg
  takwimu/takwimu_ui/src/assets/images/triangle.svg
  takwimu/takwimu_ui/src/components/Hero.js
  takwimu/takwimu_ui/src/index.js
Labels: enhancement, frontend

#485 [Staging] Profile Detail
  takwimu/static/css/takwimu.scss
  takwimu/takwimu_ui/public/index.html
  takwimu/takwimu_ui/src/assets/images/down-arrow-black.svg
  takwimu/takwimu_ui/src/assets/images/down-arrow-green.svg
  takwimu/takwimu_ui/src/assets/images/icon-search.svg
  takwimu/takwimu_ui/src/assets/images/up-arrow-black.svg
  takwimu/takwimu_ui/src/components/Navigation/index.js
  takwimu/takwimu_ui/src/components/ProfileDetail/index.js
  takwimu/takwimu_ui/src/index.js
  takwimu/templates/profile/profile_detail_base.html
Labels: enhancement, frontend

#489 [Staging] Create latest news & stories component
  takwimu/takwimu_ui/public/index.html
  takwimu/takwimu_ui/src/Theme.js
  takwimu/takwimu_ui/src/assets/images/bitmap.png
  takwimu/takwimu_ui/src/assets/images/bitmap1.png
  takwimu/takwimu_ui/src/assets/images/bitmap1@2x.png
  takwimu/takwimu_ui/src/assets/images/bitmap1@3x.png
  takwimu/takwimu_ui/src/assets/images/bitmap2.png
  takwimu/takwimu_ui/src/assets/images/bitmap2@2x.png
  takwimu/takwimu_ui/src/assets/images/bitmap2@3x.png
  takwimu/takwimu_ui/src/assets/images/bitmap@2x.png
  takwimu/takwimu_ui/src/assets/images/bitmap@3x.png
  takwimu/takwimu_ui/src/components/LatestNewsStories/Story.js
  takwimu/takwimu_ui/src/components/LatestNewsStories/StoryCard.js
  takwimu/takwimu_ui/src/components/LatestNewsStories/StoryList.js
  takwimu/takwimu_ui/src/components/LatestNewsStories/StorySummary.js
  takwimu/takwimu_ui/src/components/LatestNewsStories/index.js
  takwimu/takwimu_ui/src/components/LatestNewsStories/stories.js
  takwimu/takwimu_ui/src/index.js
Labels: enhancement

#467 Initial Design Updates - Brand Look and Feel
  takwimu/context_processors.py
  takwimu/settings.py
  takwimu/static/css/takwimu.scss
  takwimu/static/img/bg/africanparliament-detail.jpg
  takwimu/static/img/bg/africanparliament-homepage.jpg
  takwimu/static/img/bg/globe-icon.jpg
  takwimu/static/img/bg/parliament.jpg
  takwimu/static/img/bg/profile-hero-line.png
  takwimu/static/img/icons/a-chart.png
  takwimu/static/img/icons/a-chart.svg
  takwimu/static/img/icons/a-chart@2x.png
  takwimu/static/img/icons/a-chart@3x.png
  takwimu/static/img/icons/file-paragraph.png
  takwimu/static/img/icons/file-paragraph.svg
  takwimu/static/img/icons/file-paragraph@2x.png
  takwimu/static/img/icons/file-paragraph@3x.png
  takwimu/templates/404.html
  takwimu/templates/homepage.html
  takwimu/templates/takwimu/_includes/footer.html
  takwimu/templates/takwimu/_includes/homepage/carousel_item_detail.html
  takwimu/templates/takwimu/_includes/homepage/hero.html
  takwimu/templates/takwimu/_includes/navbar/_dropdown.html
  takwimu/templates/takwimu/_includes/navbar/_index.html
  takwimu/templates/takwimu/_includes/navbar/about.html
  takwimu/templates/takwimu/_includes/navbar/newsletter.html
  takwimu/templates/takwimu/_includes/navbar/search.html
  takwimu/templates/takwimu/_includes/navbar/support_services.html
  takwimu/templates/takwimu/_includes/navbar/topics.html
  takwimu/templates/takwimu/_includes/partners.html
  takwimu/templates/takwimu/_includes/profile/country_profile_downloader.html
  takwimu/templates/takwimu/_includes/profile/country_section.html
  takwimu/templates/takwimu/_includes/profile/country_selector.html
  takwimu/templates/takwimu/_includes/profile/hero.html
  takwimu/templates/takwimu/_includes/profile/sections_list.html
  takwimu/templates/takwimu/_includes/profile/sections_list_detail.html
  takwimu/templates/takwimu/_includes/profile/topic_detail.html
  takwimu/templates/takwimu/_includes/sections/explore/_index.html
  takwimu/templates/takwimu/_includes/sections/explore/countries.html
  takwimu/templates/takwimu/_includes/sections/faq/index.html
  takwimu/templates/takwimu/_includes/sections/faq/morebtn_detail.html
  takwimu/templates/takwimu/_includes/sections/how-it-works/index.html
  takwimu/templates/takwimu/_includes/sections/how-it-works/nav_detail.html
  takwimu/templates/takwimu/_includes/sections/sdg/_collapsed.html
  takwimu/templates/takwimu/_includes/sections/sdg/nav.html
  takwimu/templates/takwimu/_includes/sections/stories/index.html
  takwimu/templates/takwimu/_includes/sections/stories/story_detail.html
  takwimu/templates/takwimu/_includes/sections/support-services/button.html
  takwimu/templates/takwimu/_includes/sections/support-services/tabs.html
  takwimu/templates/takwimu/_includes/sections/testimonials.html
  takwimu/templates/takwimu/_includes/sections/updates.html
  takwimu/templates/takwimu/_layouts/_base.html
  takwimu/templates/takwimu/about/index.html
  takwimu/templates/takwimu/about/support_services.html
  takwimu/templates/takwimu/about_page.html
  takwimu/templates/takwimu/contact_us_page.html
  takwimu/templates/takwimu/sdg_topic_page.html
  takwimu/templates/takwimu/topic_page.html
  takwimu/urls.py
Labels: enhancement, frontend

#487 [Staging] New Homepage backend support
  takwimu/api.py
  takwimu/context_processors.py
  takwimu/migrations/0048_index_page_with_worldbank_data.py
  takwimu/models/dashboard.py
  takwimu/settings.py
  takwimu/templates/takwimu/home_page.html
  takwimu/urls.py
  takwimu/utils/helpers.py
  takwimu/views.py
Labels: backend, enhancement

#484 [Staging] Compile homepage
  takwimu/context_processors.py
  takwimu/models/dashboard.py
  takwimu/takwimu_ui/public/index.html
  takwimu/takwimu_ui/src/Theme.js
  takwimu/takwimu_ui/src/components/FeaturedAnalysis/AnalysisList.js
  takwimu/takwimu_ui/src/components/FeaturedAnalysis/AnalysisListItem.js
  takwimu/takwimu_ui/src/components/FeaturedAnalysis/CurrentAnalysis.js
  takwimu/takwimu_ui/src/components/FeaturedAnalysis/content.js
  takwimu/takwimu_ui/src/components/FeaturedAnalysis/index.js
  takwimu/takwimu_ui/src/components/FeaturedData/DataActions.js
  takwimu/takwimu_ui/src/components/FeaturedData/DataContainer.js
  takwimu/takwimu_ui/src/components/FeaturedData/IFrame.js
  takwimu/takwimu_ui/src/components/FeaturedData/index.js
  takwimu/takwimu_ui/src/components/Footer/Initiative.js
  takwimu/takwimu_ui/src/components/Footer/QuickLinks.js
  takwimu/takwimu_ui/src/components/Footer/StayInTouch.js
  takwimu/takwimu_ui/src/components/Footer/Support.js
  takwimu/takwimu_ui/src/components/Footer/index.js
  takwimu/takwimu_ui/src/components/Hero.js
  takwimu/takwimu_ui/src/components/LatestNewsStories/Story.js
  takwimu/takwimu_ui/src/components/LatestNewsStories/StoryBlocks.js
  takwimu/takwimu_ui/src/components/LatestNewsStories/StoryCard.js
  takwimu/takwimu_ui/src/components/LatestNewsStories/StoryList.js
  takwimu/takwimu_ui/src/components/LatestNewsStories/StorySummary.js
  takwimu/takwimu_ui/src/components/LatestNewsStories/index.js
  takwimu/takwimu_ui/src/components/LatestNewsStories/stories.js
  takwimu/takwimu_ui/src/components/Navigation/CountryAnalysis.js
  takwimu/takwimu_ui/src/components/Navigation/DataByTopic.js
  takwimu/takwimu_ui/src/components/Navigation/DropDownContent.js
  takwimu/takwimu_ui/src/components/Navigation/DropDowns.js
  takwimu/takwimu_ui/src/components/Navigation/index.js
  takwimu/takwimu_ui/src/components/WhereToNext.js
  takwimu/takwimu_ui/src/index.js
  takwimu/templates/profile/profile_detail_base.html
  takwimu/templates/takwimu/_includes/footer.html
  takwimu/templates/takwimu/_includes/navbar/_index.html
  takwimu/templates/takwimu/_layouts/_base.html
  takwimu/templates/takwimu/home_page.html
  takwimu/urls.py
Labels: backend, enhancement

#486 [Staging] Compile HURUmap profile page
  .gitignore
  Dockerfile
  takwimu/settings.py
  takwimu/sql/youth_unemployment.sql
  takwimu/static/css/takwimu.scss
  takwimu/static/js/charts.js
  takwimu/static/js/map_mapit.js
  takwimu/static/js/profile_map_mapit.js
  takwimu/takwimu_ui/public/index.html
  takwimu/takwimu_ui/src/components/Navigation/DataByTopic.js
  takwimu/takwimu_ui/src/components/Profile/Tabs.js
  takwimu/takwimu_ui/src/components/Profile/index.js
  takwimu/takwimu_ui/src/index.js
  takwimu/templates/profile/profile_detail_base.html
  takwimu/templates/profile/profile_detail_takwimu.html
  takwimu/templates/settings_js.html
  takwimu/urls.py
Labels: backend, enhancement, frontend

#494 v0.6 Hotfixes
  takwimu/migrations/0049_index_page_with_homepage_fields.py
  takwimu/models/dashboard.py
  takwimu/static/css/takwimu.scss
  takwimu/takwimu_ui/public/index.html
  takwimu/takwimu_ui/src/components/FeaturedAnalysis/index.js
  takwimu/takwimu_ui/src/components/FeaturedData/DataActions.js
  takwimu/takwimu_ui/src/components/FeaturedData/DataContainer.js
  takwimu/takwimu_ui/src/components/FeaturedData/IFrame.js
  takwimu/takwimu_ui/src/components/FeaturedData/index.js
  takwimu/takwimu_ui/src/components/Hero.js
  takwimu/takwimu_ui/src/components/LatestNewsStories/index.js
  takwimu/takwimu_ui/src/components/MakingOfTakwimu.js
  takwimu/takwimu_ui/src/components/Navigation/DataByTopic.js
  takwimu/takwimu_ui/src/components/ProfileDetail/index.js
  takwimu/takwimu_ui/src/components/WhatCanYouDo.js
  takwimu/takwimu_ui/src/index.js
Labels: backend, data, enhancement

#491 [Staging] Unify *Next components
  takwimu/takwimu_ui/public/index.html
  takwimu/takwimu_ui/src/components/FeaturedData/index.js
  takwimu/takwimu_ui/src/components/Next/About.js
  takwimu/takwimu_ui/src/components/Next/Analysis.js
  takwimu/takwimu_ui/src/components/Next/Card.js
  takwimu/takwimu_ui/src/components/Next/Home.js
  takwimu/takwimu_ui/src/components/Next/index.js
  takwimu/takwimu_ui/src/components/WhereToNext.js
  takwimu/takwimu_ui/src/index.js
Labels: enhancement

#493 [Staging] Create View Country component
  takwimu/takwimu_ui/public/index.html
  takwimu/takwimu_ui/src/Theme.js
  takwimu/takwimu_ui/src/components/Navigation/CountryAnalysis.js
  takwimu/takwimu_ui/src/components/Navigation/DataByTopic.js
  takwimu/takwimu_ui/src/components/ViewCountry/Selection.js
  takwimu/takwimu_ui/src/components/ViewCountry/index.js
  takwimu/takwimu_ui/src/index.js
  takwimu/templates/takwimu/profile_page.html
  takwimu/utils/helpers.py
Labels: enhancement

#492 [Staging] Create related content component
  takwimu/takwimu_ui/public/index.html
  takwimu/takwimu_ui/src/Theme.js
  takwimu/takwimu_ui/src/components/Navigation/CountryAnalysis.js
  takwimu/takwimu_ui/src/components/Navigation/DataByTopic.js
  takwimu/takwimu_ui/src/components/Navigation/DropDownContent.js
  takwimu/takwimu_ui/src/components/Navigation/index.js
  takwimu/takwimu_ui/src/components/RelatedContent/Links.js
  takwimu/takwimu_ui/src/components/RelatedContent/index.js
  takwimu/takwimu_ui/src/index.js
  takwimu/templates/takwimu/about/index.html
  takwimu/templates/takwimu/profile_page.html
Labels: enhancement

#495 [Staging] Add Related content on dashboard
  takwimu/migrations/0050_related_content.py
  takwimu/models/dashboard.py
Labels: backend

#490 [Staging] Analysis Page
  takwimu/models/dashboard.py
  takwimu/takwimu_ui/public/index.html
  takwimu/takwimu_ui/src/assets/images/active-page.svg
  takwimu/takwimu_ui/src/assets/images/analysis/download.svg
  takwimu/takwimu_ui/src/assets/images/analysis/share.svg
  takwimu/takwimu_ui/src/components/AnalysisContent/Actions.js
  takwimu/takwimu_ui/src/components/AnalysisContent/OtherInfo.js
  takwimu/takwimu_ui/src/components/AnalysisContent/OtherInfoNav.js
  takwimu/takwimu_ui/src/components/AnalysisContent/TableOfContent.js
  takwimu/takwimu_ui/src/components/AnalysisContent/index.js
  takwimu/takwimu_ui/src/components/Footer/index.js
  takwimu/takwimu_ui/src/components/Navigation/DropDownButton.js
  takwimu/takwimu_ui/src/components/Navigation/DropDowns.js
  takwimu/takwimu_ui/src/components/Navigation/index.js
  takwimu/takwimu_ui/src/components/Next/Analysis.js
  takwimu/takwimu_ui/src/components/Next/Card.js
  takwimu/takwimu_ui/src/components/ProfileDetail/index.js
  takwimu/takwimu_ui/src/components/ViewCountry/Selection.js
  takwimu/takwimu_ui/src/index.js
  takwimu/takwimu_ui/src/pages/AnalysisPage/index.js
  takwimu/templates/profile/profile_detail_base.html
  takwimu/templates/takwimu/home_page.html
  takwimu/templates/takwimu/profile_page.html
  takwimu/urls.py
Labels: enhancement, frontend

#498 [Staging] Create FAQ component
  takwimu/takwimu_ui/public/index.html
  takwimu/takwimu_ui/src/components/Faqs/Faq.js
  takwimu/takwimu_ui/src/components/Faqs/index.js
  takwimu/takwimu_ui/src/index.js
  takwimu/takwimu_ui/yarn.lock
  yarn.lock
Labels: enhancement

#501 [Staging] Compile Analysis page
  takwimu/models/dashboard.py
  takwimu/takwimu_ui/package.json
  takwimu/takwimu_ui/public/embed/iframe.html
  takwimu/takwimu_ui/public/index.html
  takwimu/takwimu_ui/src/Theme.js
  takwimu/takwimu_ui/src/components/AnalysisContent/Actions.js
  takwimu/takwimu_ui/src/components/AnalysisContent/OtherInfo.js
  takwimu/takwimu_ui/src/components/AnalysisContent/OtherInfoNav.js
  takwimu/takwimu_ui/src/components/AnalysisContent/TableOfContent.js
  takwimu/takwimu_ui/src/components/AnalysisContent/index.js
  takwimu/takwimu_ui/src/components/FeaturedAnalysis/index.js
  takwimu/takwimu_ui/src/components/FeaturedData/DataContainer.js
  takwimu/takwimu_ui/src/components/FeaturedData/IFrame.js
  takwimu/takwimu_ui/src/components/FeaturedData/index.js
  takwimu/takwimu_ui/src/components/Navigation/DropDowns.js
  takwimu/takwimu_ui/src/components/Navigation/index.js
  takwimu/takwimu_ui/src/components/Next/Analysis.js
  takwimu/takwimu_ui/src/components/Next/Card.js
  takwimu/takwimu_ui/src/components/Profile/Tabs.js
  takwimu/takwimu_ui/src/components/RelatedContent/Links.js
  takwimu/takwimu_ui/src/components/RelatedContent/index.js
  takwimu/takwimu_ui/src/components/ViewCountry/Selection.js
  takwimu/takwimu_ui/src/components/ViewCountry/index.js
  takwimu/takwimu_ui/src/index.js
  takwimu/takwimu_ui/src/pages/AnalysisPage/index.js
Labels: backend, enhancement, frontend

#502 [Staging] [Hotfix] Ensure takwimu.page.id
  takwimu/takwimu_ui/public/index.html
  takwimu/templates/profile/profile_detail_base.html
  takwimu/templates/takwimu/about/index.html
  takwimu/templates/takwimu/contact_us_page.html
  takwimu/templates/takwimu/home_page.html
  takwimu/templates/takwimu/profile_page.html
Labels: bug, frontend

#500 [Staging] Country Analysis backend redesign
  takwimu/migrations/0051_migrate_topic_to_freeform.py
  takwimu/models/dashboard.py
Labels: backend, enhancement

#497 [Staging] [Feature] Compile About us page
  takwimu/migrations/0052_aboutpage_methodology.py
  takwimu/migrations/0053_supportservicessetting_overview.py
  takwimu/migrations/0054_faqsetting_overview.py
  takwimu/models/dashboard.py
  takwimu/takwimu_ui/public/index.html
  takwimu/takwimu_ui/src/Theme.js
  takwimu/takwimu_ui/src/components/AboutUsContent/AboutUsContentNav.js
  takwimu/takwimu_ui/src/components/AboutUsContent/ContentNavigation.js
  takwimu/takwimu_ui/src/components/AboutUsContent/TableOfContent.js
  takwimu/takwimu_ui/src/components/AboutUsContent/index.js
  takwimu/takwimu_ui/src/components/AnalysisContent/ContentNavigation.js
  takwimu/takwimu_ui/src/components/AnalysisContent/OtherInfo.js
  takwimu/takwimu_ui/src/components/AnalysisContent/TableOfContent.js
  takwimu/takwimu_ui/src/components/AnalysisContent/index.js
  takwimu/takwimu_ui/src/components/ContentNavigation.js
  takwimu/takwimu_ui/src/components/ContentPage.js
  takwimu/takwimu_ui/src/components/ContentSection.js
  takwimu/takwimu_ui/src/components/Faqs/Faq.js
  takwimu/takwimu_ui/src/components/Faqs/index.js
  takwimu/takwimu_ui/src/components/Layout.js
  takwimu/takwimu_ui/src/components/Next/About.js
  takwimu/takwimu_ui/src/components/RelatedContent/index.js
  takwimu/takwimu_ui/src/components/RichTextSection.js
  takwimu/takwimu_ui/src/components/Section.js
  takwimu/takwimu_ui/src/components/Services.js
  takwimu/takwimu_ui/src/components/TableOfContent.js
  takwimu/takwimu_ui/src/index.js
  takwimu/takwimu_ui/src/pages/AboutUs.js
  takwimu/takwimu_ui/src/pages/Analysis.js
  takwimu/takwimu_ui/yarn.lock
  takwimu/templates/takwimu/_layouts/_base.html
  takwimu/templates/takwimu/about/index.html
  takwimu/views.py
Labels: backend, enhancement, frontend

#504 [Staging] Analysis page content with indicators
  takwimu/takwimu_ui/package.json
  takwimu/takwimu_ui/src/components/AboutUsContent/index.js
  takwimu/takwimu_ui/src/components/AnalysisContent/OtherInfoNav.js
  takwimu/takwimu_ui/src/components/AnalysisContent/index.js
  takwimu/takwimu_ui/src/components/Faqs/Faq.js
  takwimu/takwimu_ui/src/components/Faqs/index.js
  takwimu/takwimu_ui/src/components/FeaturedData/DataContainer.js
  takwimu/takwimu_ui/src/components/Next/Analysis.js
  takwimu/takwimu_ui/src/components/Services.js
  takwimu/takwimu_ui/yarn.lock
Labels: backend, design, enhancement, frontend

#509 [Staging] Fix remove shadow in drawer
  takwimu/takwimu_ui/src/components/Navigation/index.js
Labels: bug, design, frontend

#507 [Staging] Fix Featured Data not Displaying
  takwimu/takwimu_ui/src/components/AnalysisContent/index.js
  takwimu/takwimu_ui/src/components/FeaturedData/DataContainer.js
  takwimu/takwimu_ui/src/components/FeaturedData/index.js
Labels: bug

#512 [Staging] Allow url hash to work
  takwimu/takwimu_ui/src/components/AnalysisContent/ContentNavigation.js
  takwimu/takwimu_ui/src/components/AnalysisContent/OtherInfoNav.js
  takwimu/takwimu_ui/src/components/ContentNavigation.js
  takwimu/takwimu_ui/src/components/Faqs/Faq.js
  takwimu/takwimu_ui/src/pages/Analysis.js
Labels: bug, enhancement, frontend

#510 [Staging] Add missing shadow to other info navigation bar
  takwimu/takwimu_ui/src/components/AboutUsContent/AboutUsContentNav.js
  takwimu/takwimu_ui/src/components/AnalysisContent/OtherInfoNav.js
  takwimu/takwimu_ui/src/useScrollListener.js
Labels: bug, design, frontend

#513 [Staging] Fix Nav Dropdown
  takwimu/takwimu_ui/src/components/AnalysisContent/OtherInfoNav.js
  takwimu/takwimu_ui/src/components/Navigation/DropDownButton.js
Labels: bug, frontend

#515 [Staging] Minor fix use settings medium link
  takwimu/takwimu_ui/src/components/LatestNewsStories/index.js
Labels: bug

#506 [Staging] Freeform Topics indexing
  takwimu/management/commands/update_topics_index.py
  takwimu/migrations/0055_indicatorblock_summary.py
  takwimu/models/dashboard.py
  takwimu/search/takwimu_search.py
  takwimu/search/utils.py
  takwimu/urls.py
  takwimu/views.py
Labels: backend, data, enhancement

#499 [Staging] Search
  takwimu/takwimu_ui/src/assets/images/right-arrow-transparent.svg
  takwimu/takwimu_ui/src/assets/images/right-arrow.svg
  takwimu/takwimu_ui/src/components/Navigation/SearchDrawer.js
  takwimu/takwimu_ui/src/components/Navigation/index.js
Labels: enhancement
