Repository TakwimuAfrica/Takwimu, pull requests merged in 2019-06, with the labels that each got.

#572 [Staging] Kenya data on HURUmap
  takwimu/fixtures/wazimap.json
  takwimu/profiles/census.py
  takwimu/sql/employment_in_agriculture.sql
  takwimu/sql/health_workers_distribution.sql
  takwimu/sql/infant_under5_mortality.sql
  takwimu/sql/women_in_government.sql
  takwimu/sql/women_in_parliament.sql
  takwimu/tables.py
  takwimu/templates/profile/profile_detail_takwimu.html
Labels: backend, data, enhancement

#576 [FIX] Map interaction
  takwimu/static/js/profile_map_mapit.js
  takwimu/takwimu_ui/src/components/ProfileDetail/index.js
Labels: bug

#578 Improve Data by Topic charts Overflow & Download
  takwimu/static/css/takwimu.scss
  takwimu/static/js/charts.js
  takwimu/templates/takwimu/_includes/dataview/image.html
Labels: data, design, frontend

#589 Ensure charts have minimum height
  takwimu/static/css/embedchart.scss
  takwimu/static/css/takwimu.scss
  takwimu/static/js/charts.js
  takwimu/static/js/profile_map_mapit.js
  takwimu/takwimu_ui/src/components/DataContainer/FlourishDataContainer.js
  takwimu/takwimu_ui/src/components/DataContainer/IFrame.js
Labels: bug, enhancement, frontend

#591 Fix content page aside overflow and scroll
  takwimu/takwimu_ui/src/components/AnalysisContent/index.js
  takwimu/takwimu_ui/src/components/TableOfContent.js
  takwimu/takwimu_ui/src/pages/Analysis.js
Labels: bug, design, enhancement

#592 [Hotfix] favicon static import
  takwimu/templates/takwimu/_layouts/_base.html
Labels: bug, frontend

#593 Improve Build
  takwimu/context_processors.py
  takwimu/takwimu_ui/.babelrc
  takwimu/takwimu_ui/.eslintrc.json
  takwimu/takwimu_ui/package.json
  takwimu/takwimu_ui/src/components/AnalysisContent/Actions/DownloadPDF.js
  takwimu/takwimu_ui/src/components/AnalysisContent/Actions/index.js
  takwimu/takwimu_ui/src/components/AnalysisContent/index.js
  takwimu/takwimu_ui/src/components/DataContainer/PDFDataContainer.js
  takwimu/takwimu_ui/src/modules/pdf.js
  takwimu/takwimu_ui/src/modules/react-pdf.js
  takwimu/takwimu_ui/yarn.lock
  takwimu/templates/takwimu/_layouts/_base.html
Labels: dependencies, enhancement, frontend

#595 [Hotfix] Microsoft Edge support
  takwimu/takwimu_ui/package.json
  takwimu/takwimu_ui/src/index.js
  takwimu/takwimu_ui/yarn.lock
  takwimu/templates/data/_base_data.html
  takwimu/templates/profile/profile_detail_base.html
  takwimu/templates/takwimu/_includes/footer.html
  takwimu/templates/takwimu/home_page.html
Labels: bug, dependencies, enhancement, frontend

#596 Google Analytics
  takwimu/static/js/charts.js
  takwimu/takwimu_ui/src/Theme.js
  takwimu/takwimu_ui/src/components/AnalysisContent/Actions/DownloadPDF.js
  takwimu/takwimu_ui/src/components/AnalysisContent/Actions/index.js
  takwimu/takwimu_ui/src/components/AnalysisContent/index.js
  takwimu/takwimu_ui/src/components/DataContainer/DataActions.js
  takwimu/takwimu_ui/src/components/DataContainer/EntitiesDataContainer.js
  takwimu/takwimu_ui/src/components/DataContainer/FlourishDataContainer.js
  takwimu/takwimu_ui/src/components/DataContainer/HTMLDataContainer.js
  takwimu/takwimu_ui/src/components/DataContainer/HurumapDataContainer.js
  takwimu/takwimu_ui/src/components/DataContainer/ImageDataContainer.js
  takwimu/takwimu_ui/src/components/DataContainer/PDFDataContainer.js
  takwimu/takwimu_ui/src/components/DataContainer/index.js
  takwimu/takwimu_ui/src/components/FeaturedData.js
  takwimu/takwimu_ui/src/components/MakingOfTakwimu.js
  takwimu/templates/ga_scripts.html
  takwimu/templates/profile/profile_detail_base.html
  takwimu/templates/takwimu/_layouts/_base.html
Labels: enhancement
