Repository TakwimuAfrica/Takwimu, pull requests merged in 2019-07, with the labels that each got.

#597 Page load/ajax requests indicator
  takwimu/settings.py
  takwimu/takwimu_ui/public/index.html
  takwimu/takwimu_ui/public/pace.css
  takwimu/takwimu_ui/public/pace.min.js
  takwimu/templates/profile/profile_detail_base.html
  takwimu/templates/takwimu/_layouts/_base.html
Labels: enhancement, frontend

#598 Update HURUmap & cleanup templates
  Dockerfile
  takwimu/templates/data/_base_data.html
  takwimu/templates/data/data_map.html
  takwimu/templates/profile/profile_detail_base.html
Labels: bug, enhancement, frontend

#601 Add custom 500 error page
  takwimu/takwimu_ui/public/index.html
  takwimu/takwimu_ui/src/components/Error.js
  takwimu/takwimu_ui/src/components/ErrorPage.js
  takwimu/takwimu_ui/src/index.js
  takwimu/takwimu_ui/src/pages/500.js
  takwimu/templates/500.html
  takwimu/urls.py
  takwimu/views.py
Labels: backend, design, enhancement, frontend

#605 Fix Carousel topic load error
  takwimu/takwimu_ui/src/components/AnalysisContent/Actions/DownloadPDF.js
  takwimu/takwimu_ui/src/components/AnalysisContent/index.js
Labels: bug, frontend

#606 Fix static path reference in JavaScript files
  takwimu/static/js/charts.js
  takwimu/templates/settings_js.html
Labels: bug, enhancement, frontend

#607 Data by Topic chart stat list
  takwimu/profiles/census.py
  takwimu/static/css/takwimu.scss
  takwimu/templates/profile/profile_detail_takwimu.html
Labels: Experiment, data
