Repository TakwimuAfrica/Takwimu, pull requests merged in 2019-02, with the labels that each got.

#452 Remove Zendesk [163477853]
  takwimu/forms.py
  takwimu/migrations/0044_supportsetting_support.py
  takwimu/models/dashboard.py
  takwimu/settings.py
  takwimu/templates/500.html
  takwimu/templates/homepage.html
  takwimu/templates/profile/profile_detail_base.html
  takwimu/templates/takwimu/_includes/homepage/carousel_item_detail.html
  takwimu/templates/takwimu/_includes/navbar/support_services.html
  takwimu/templates/takwimu/_includes/profile/topic_detail.html
  takwimu/templates/takwimu/_includes/sections/faq/morebtn_detail.html
  takwimu/templates/takwimu/_includes/sections/updates.html
  takwimu/templates/takwimu/_includes/topic.html
  takwimu/templates/takwimu/_layouts/_base.html
  takwimu/templates/takwimu/about/contact.html
  takwimu/templates/takwimu/about/support_services.html
  takwimu/templates/takwimu/contact_us_page.html
  takwimu/views.py
Labels: backend, bug, enhancement, frontend

#455 Twitter Card Support
  docker-compose.yml
  requirements.txt
  takwimu/migrations/0045_profilepage_meta.py
  takwimu/models/dashboard.py
  takwimu/settings.py
  takwimu/templates/takwimu/_layouts/_base.html
Labels: enhancement

#447 Upgrade to Releases
  Dockerfile
  docker-entrypoint.sh
  requirements.txt
  takwimu/data/__init__.py
  takwimu/data/utils.py
  takwimu/fixtures/takwimu_wazimap_fixtures.json
  takwimu/profiles/census.py
  takwimu/settings.py
  takwimu/sql/incidence_of_malaria_per_1000_pop_at_risk.sql
  takwimu/sql/population_residence_2009.sql
  takwimu/sql/population_residence_2012.sql
  takwimu/sql/population_residence_2013.sql
  takwimu/sql/population_sex.sql
  takwimu/sql/population_sex_2006.sql
  takwimu/sql/population_sex_2007.sql
  takwimu/sql/population_sex_2009.sql
  takwimu/sql/population_sex_2011.sql
  takwimu/sql/population_sex_2012.sql
  takwimu/sql/population_sex_2013.sql
  takwimu/tables.py
  takwimu/templates/profile/profile_detail_takwimu.html
  takwimu/urls.py
  takwimu/views.py
Labels: backend, enhancement

#441 Use the new HURUmap docker
  .travis.yml
  Dockerfile
  Makefile
  README.md
  VERSION
  contrib/docker/release-build.sh
  contrib/docker/release.sh
  contrib/loaddata.sh
  docker-compose.yml
  docker-entrypoint.sh
  requirements.txt
  takwimu/context_processors.py
  takwimu/fixtures/takwimu_wazimap_fixtures.json
  takwimu/fixtures/wazimap.json
  takwimu/profiles/census.py
  takwimu/tables.py
  takwimu/urls.py
  takwimu/wsgi.py
Labels: enhancement

#456 Add Mapit to Takwimu
  takwimu/data/utils.py
  takwimu/management/commands/upgradetables.py
  takwimu/profiles/census.py
  takwimu/settings.py
  takwimu/sql/wazimap_geography.sql
  takwimu/static/js/map_mapit.js
  takwimu/static/js/profile_map_mapit.js
  takwimu/templates/profile/profile_detail_base.html
Labels: backend, data, enhancement
